### ISSUE TITLE
Plugin not working on Mac...

### ISSUE THREAD

**Issue by hannahgrace1234** [Palakis/obs-ndi#399] opened 2020-03-17 11:19 UTC
Hi, I have been trying to download for mac and am having a lot of trouble. I have tried multiple times on both my macbook (mojave) and my imac (catalina) and neither are working. The installer will run and then nothing happens and I can't find the file anywhere to drag into the plugins folder myself. Can someone please help me work out what is going wrong? I really need the plugin to be able to link skype during my livestream.

**Comment by celbasi** [comment] 2020-03-19 13:52
same for me on catalina

**Comment by makeitTim** [comment] 2020-03-19 16:34
Mojave. Cannot even install.

**Comment by gleasonmagic79** [comment] 2020-03-23 05:16
I'm having the same problem...Catalina 10.15.3

**Comment by Auto-moto-kyoto** [comment] 2020-03-23 15:53
I have the same issue exactly, i'm also on 10.15.3 and plug in 4.7.1 - I get the same warning.

**Comment by Palakis** [comment] 2020-03-24 14:36
Duplicate of #385

**Closed by Palakis** 2020-03-24 14:36 UTC
