### ISSUE TITLE
[Win10-OSX] Black Screen of Death

### ISSUE THREAD

**Issue by AscenAudio** [Palakis/obs-ndi#367] opened 2019-11-10 06:23 UTC
After hours of research I thought I found the best way to go about streaming my laptop to my PC. My main goal with this program is to send video from my under powered Macbook Pro 2016 to my gaming/desktop PC to then stream/record from there. I want to take this route because there are specific programs that I either prefer to use on Mac or is only available on that OS. 

Here is the problem: I've tried restarting, reinstalling both OBS and the NDI plugin, Firewall preferences, enabling media streaming, and disabling all networks except what is connected to the router. Yet after all of this I still get nothing on my screen. Black and empty. NDI monitor shows nothing either. I tried streaming my PC to my mac and got no luck. I tried the opposite and had the same result. I tried streaming my PC to my PC and still could get nothing to show. I really REALLY want this program to work, and am willing to try nearly anything you tech gurus can think of.

Also, I am pretty average when it comes to technology so please bear with me

**Comment by OnkelTem** [comment] 2019-12-09 11:58
Yeah, it just doesn't work.

They said: NDI will help you. Yeah, it helped to spent another few hours for nothing. For 29 days nobody answered, is also a bad sign.

**Comment by OnkelTem** [comment] 2019-12-09 12:12
```
15:01:23.954: CPU Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
15:01:23.955: CPU Speed: 1992MHz
15:01:23.955: Physical Cores: 4, Logical Cores: 8
15:01:23.955: Physical Memory: 16276MB Total, 10602MB Free
15:01:23.955: Windows Version: 10.0 Build 18362 (revision: 476; 64-bit)
15:01:23.955: Running as administrator: false
15:01:23.955: Aero is Enabled (Aero is always on for windows 8 and above)
15:01:23.955: Windows 10 Gaming Features:
15:01:23.955: 	Game DVR: On
15:01:23.956: Sec. Software Status:
15:01:23.958: 	Windows Defender Antivirus: enabled (AV)
15:01:23.958: 	Windows Firewall: enabled (FW)
15:01:23.959: Current Date/Time: 2019-12-09, 15:01:23
15:01:23.959: Browser Hardware Acceleration: true
15:01:23.959: Portable mode: false
15:01:24.245: OBS 24.0.3 (64-bit, windows)
15:01:24.245: ---------------------------------
15:01:24.271: ---------------------------------
15:01:24.271: audio settings reset:
15:01:24.271: 	samples per sec: 44100
15:01:24.271: 	speakers:        2
15:01:24.272: ---------------------------------
15:01:24.272: Initializing D3D11...
15:01:24.272: Available Video Adapters: 
15:01:24.274: 	Adapter 0: Intel(R) UHD Graphics 620
15:01:24.274: 	  Dedicated VRAM: 134217728
15:01:24.274: 	  Shared VRAM:    4238481408
15:01:24.274: 	  output 0: pos={0, 0}, size={3200, 1800}, attached=true
15:01:24.277: Loading up D3D11 on adapter Intel(R) UHD Graphics 620 (0)
15:01:24.294: D3D11 loaded successfully, feature level used: b000
15:01:24.742: ---------------------------------
15:01:24.742: video settings reset:
15:01:24.742: 	base resolution:   1920x1080
15:01:24.742: 	output resolution: 1280x720
15:01:24.742: 	downscale filter:  Bicubic
15:01:24.742: 	fps:               30/1
15:01:24.742: 	format:            NV12
15:01:24.742: 	YUV mode:          601/Partial
15:01:24.742: NV12 texture support not available
15:01:24.743: Audio monitoring device:
15:01:24.743: 	name: Default
15:01:24.743: 	id: default
15:01:24.743: ---------------------------------
15:01:24.746: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
15:01:24.746: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
15:01:24.784: [AMF] AMF Test failed due to one or more errors.
15:01:24.784: Failed to initialize module 'enc-amf.dll'
15:01:24.801: [obs-browser]: Version 2.7.15
15:01:24.801: [obs-browser]: Blacklisted device detected, disabling browser source hardware acceleration.
15:01:24.805: [obs-ndi] hello ! (version 4.7.1)
15:01:24.805: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
15:01:24.805: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
15:01:24.808: [obs-ndi] NDI runtime loaded successfully
15:01:24.811: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:56:42 Nov 15 2019 4.1.3.0)
15:01:24.832: Couldn't find VLC installation, VLC video source disabled
15:01:24.835: No blackmagic support
15:01:24.839: ---------------------------------
15:01:24.839:   Loaded Modules:
15:01:24.839:     win-wasapi.dll
15:01:24.839:     win-mf.dll
15:01:24.839:     win-dshow.dll
15:01:24.839:     win-decklink.dll
15:01:24.839:     win-capture.dll
15:01:24.839:     vlc-video.dll
15:01:24.839:     text-freetype2.dll
15:01:24.839:     rtmp-services.dll
15:01:24.839:     obs-x264.dll
15:01:24.839:     obs-vst.dll
15:01:24.839:     obs-transitions.dll
15:01:24.839:     obs-text.dll
15:01:24.839:     obs-qsv11.dll
15:01:24.839:     obs-outputs.dll
15:01:24.839:     obs-ndi.dll
15:01:24.839:     obs-filters.dll
15:01:24.839:     obs-ffmpeg.dll
15:01:24.839:     obs-browser.dll
15:01:24.839:     image-source.dll
15:01:24.839:     frontend-tools.dll
15:01:24.839:     enc-amf.dll
15:01:24.839:     decklink-ouput-ui.dll
15:01:24.839:     coreaudio-encoder.dll
15:01:24.839: ---------------------------------
15:01:24.839: ==== Startup complete ===============================================
15:01:24.840: Service '' not found
15:01:24.842: All scene data cleared
15:01:24.842: ------------------------------------------------
15:01:24.883: WASAPI: Device 'Speakers (Razer Surround Audio Controller)' initialized
15:01:25.027: WASAPI: Device 'Microphone (Realtek High Definition Audio)' initialized
15:01:25.027: Switched to scene 'Scene'
15:01:25.027: ------------------------------------------------
15:01:25.027: Loaded scenes:
15:01:25.027: - scene 'Scene':
15:01:25.027: ------------------------------------------------
15:01:25.061: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds (source: Mic/Aux)
15:01:25.061: 
15:01:37.886: [obs-ndi] started A/V threads for source ''
15:01:37.886: [obs-ndi] A/V thread for 'NDI™ Source' started
15:01:37.889: User added source 'NDI™ Source' (ndi_source) to scene 'Scene'
15:01:47.339: [obs-ndi] audio thread for 'NDI™ Source' completed
15:01:47.340: [obs-ndi] started A/V threads for source 'LAPTOP-xxxxxxx (Skype - (Local))'
15:01:47.340: [obs-ndi] A/V thread for 'NDI™ Source' started
15:06:47.787: [obs-ndi] audio thread for 'NDI™ Source' completed
15:06:47.789: [obs-ndi] started A/V threads for source 'LAPTOP-xxxxxxx (Skype - [live] cid caaabxxxx)'
15:06:47.789: [obs-ndi] A/V thread for 'NDI™ Source' started
15:06:54.425: [obs-ndi] audio thread for 'NDI™ Source' completed
15:06:54.430: [obs-ndi] started A/V threads for source 'LAPTOP-xxxxxxx (Skype - Active Speaker)'
15:06:54.431: [obs-ndi] A/V thread for 'NDI™ Source' started

```

Right after adding the source it shows just a black screen with right dot in the top left corner:
![Black screen 1](https://i.gyazo.com/f2768c7f2cc6046d411ffac4d3fc732f.png)

Fitting it to the screen gives the same black screen:
![Black screen 1](https://i.gyazo.com/a6fdaf2321e0b8470fff0ac556370f29.png)

**Comment by OnkelTem** [comment] 2019-12-09 12:16
@Palakis , would you please have a look?

**Comment by Palakis** [comment] 2019-12-09 12:34
@OnkelTem Gonna take a look whenever I have some time.

> For 29 days nobody answered, is also a bad sign.

I've been pretty busy for the past month. If someone is willing to give me a hand to develop and maintain obs-ndi, my DMs on Twitter are open.

**Comment by OnkelTem** [comment] 2019-12-09 18:30
> I've been pretty busy for the past month. If someone is willing to give me a hand to develop and maintain obs-ndi, my DMs on Twitter are open.

I would help, but I'm a user :)

**Comment by WaldoFuss** [comment] 2020-02-11 00:07
hello, I solved that problem by deactivating the firewall on both pc.

**Comment by Vigrond** [comment] 2020-02-21 16:49
Same exact issue with Windows source and Ubuntu streaming and visa versa.

Deactivating firewall / antivirus.  Allowing ports on ufw do nothing.  Nothing in the logs.

**Comment by Palakis** [comment] 2020-03-24 13:09
@OnkelTem 
> I would help, but I'm a user :)

Help from users is very very welcome! As you can notice, the Issues section here is in a pretty bad shape and I could use a hand for issues triage.

Regarding your issue, have you tried manually adding OBS to your systems' firewall exceptions?

**Comment by Palakis** [comment] 2020-03-24 14:06
Duplicate of #62

**Closed by Palakis** 2020-03-24 14:06 UTC
Labels: duplicate, video

**Comment by IzicastDev** [comment] 2022-07-28 08:38
The same here. I desactivated the Firewall but nothing happen. To be honest I'm tired of NDI. The afford is too big to put something to work. I advise my company to not use it. most of the TV stations I work with stop using it.

I hope some company has the chance to develop something stable and rock solid as a simple cable connection.
