### ISSUE TITLE
Flickering/wobbly lines with interleaved output

### ISSUE THREAD

**Issue by patmu** [Palakis/obs-ndi#45] opened 2017-08-27 21:18 UTC
Testing NDI plugin version 4.1.1: If source is an NDI 720p50 stream, the generated NDI output is 720i50.

This doesn't happen with NDI plugin version 4.1.0.

**Comment by Palakis** [comment] 2017-08-28 07:53
On the NDI Program Output, there's noticeable tearing at 200fps in progressive video which doesn't appear with interleaved video. Testing on my end showed no difference between progressive and interleaved video at 60fps when receiving with NewTek's Studio Monitor, so I decided to introduce this fix in 4.1.1

Here's for my explanation. Does this causes problems in your setup?

**Comment by patmu** [comment] 2017-08-28 08:14
Yes, this causes problems in my setup. I'm also testing with NDI Studio Monitor and get a lot of flickering there.

But I will test again and post the results.

**Comment by patmu** [comment] 2017-08-28 19:13
I tested again and there is a flickering on OBS NDI ouput.

I made a short example video: https://youtu.be/vQ9_-1KhfIU
0-15sec: original NDI stream
>16sec: switch to OBS NDI output

One solution could be having a dropdown list (progressiv/interleaved) in NDI Output settings and letting the user decide about the frame type.

**Comment by Palakis** [comment] 2017-08-31 17:33
Thanks for the video sample! Video looks wobbly indeed.

> One solution could be having a dropdown list (progressiv/interleaved) in NDI Output settings and letting the user decide about the frame type.

Agreed!

**Comment by kanelp** [comment] 2017-09-06 22:33
I too am seeing this issue with v4.1.1, while v4.1.0 is okay.  If I had to guess, it appears that the NDI output is being tagged as an interlaced video format.

**Comment by Palakis** [comment] 2017-09-07 12:24
> it appears that the NDI output is being tagged as an interlaced video format.

It is. But I've had this wrong because the issue that led me to set it to interleaved was caused by a deeper design problem.

**Comment by Palakis** [comment] 2017-09-07 12:24
Anyway, this has been fixed in the latest commits.

**Closed by Palakis** 2017-09-07 12:24 UTC
Labels: bug

**Comment by Sephiroth1983** [comment] 2019-09-05 19:33
If someone happens to still have a flickering with OBS NDI at the bottom of their Gsync screen (which usually requires Vsync ON in nvidia control panel, but disabled in games), it's a matter of disabling VSync just for the OBS profile.
