### ISSUE TITLE
Can't select NDI as a source in OBS on MacOS Catalina 

### ISSUE THREAD

**Issue by Connormcquade** [Palakis/obs-ndi#419] opened 2020-04-04 15:17 UTC
Have tried downloading the NDI runtime manually which installs. However, when I go onto OBS and try to select NDI as a source it doesn't give me the option. 

I have also tried disabling SIP on my mac and downloading the obs-ndi-4.7.1-macOS.pkg but I get the following error message 

<img width="422" alt="Screenshot 2020-04-04 at 16 16 57" src="https://user-images.githubusercontent.com/63157709/78454395-bb1f1a00-768f-11ea-958b-60ee15c7cb18.png">

Can anyone provide me with a solution for this? 

Thanks

**Comment by mitsol** [comment] 2020-04-04 16:59
It is usually the case with files that MacOS doesn't trust. Try the following: find the file in finder and press right mouse button to get the context menu. In the context menu click "open". Now you should get a similar but subtle different dialog, where you can select "open" anyway.

**Comment by Connormcquade** [comment] 2020-04-04 17:01
> It is usually the case with files that MacOS doesn't trust. Try the following: find the file in finder and press right mouse button to get the context menu. In the context menu click "open". Now you should get a similar but subtle different dialog, where you can select "open" anyway.

Thanks, worked perfectly!

**Comment by Palakis** [comment] 2020-04-06 14:54
Duplicate of #385

**Closed by Palakis** 2020-04-06 14:54 UTC
