### ISSUE TITLE
DUAL PC black screen window capture on NDI Output

### ISSUE THREAD

**Issue by RHSJack** [Palakis/obs-ndi#159] opened 2018-05-02 14:51 UTC
Game and audio capture work fine on gaming PC to streaming PC. Previously, window capture can grab browser window but as of today shows black screen. OBS still recognizes browser window but shows only black screen. Reset NDI, reset TCP. Turned off ad block on chrome and turned off firewall, reset switch and PC. Am I missing something or should I post a log? And  which OBS log should I post, outputing pc or streaming pc?

**Comment by Palakis** [comment] 2018-05-02 15:11
@RHSJack Post a log, please. By the way, on first look this doesn't look like an issue related to NDI, but more likely to a recent OS update.

**Comment by RHSJack** [comment] 2018-05-03 01:32
I see. I can definitely believe that. Here is the OBS log file...
[2018-05-03 09-31-25jb.txt](https://github.com/Palakis/obs-ndi/files/1969367/2018-05-03.09-31-25jb.txt)

**Comment by Helgaiden** [comment] 2018-05-03 15:13
If this is google chrome you're talking about for window capture, you need to turn off hardware acceleration in its settings (same might go for other browsers).

**Comment by RHSJack** [comment] 2018-05-03 15:19
No dice. Toggled both. And usually the issue is either/or. And I am coming across other issues not related to this thread (audio, off sync, etc) so I am guessing I need to be a little patient with patches.

**Comment by RHSJack** [comment] 2018-05-04 03:15
I have reinstalled OBS and NDI on both streaming/gaming PCs. I turned on the privacy settings (as in I granted permission...someone said that might be an thing) and checked hardware acceleration. This is so weird. Only window capture has black screen. And game capture works but I can't hear audio (stream can hear tho). Genuinely befuddled by this. Defies logic.

**Comment by RHSJack** [comment] 2018-05-08 14:45
Ping.

**Comment by Palakis** [comment] 2020-03-24 13:31
I'm doing a bit of triaging and closing duplicates. This one is a duplicate of #62

**Closed by Palakis** 2020-03-24 13:31 UTC
Labels: black-screen, incomplete, no-signal
