### ISSUE TITLE
OBS NDI plug in not working on MAC...

### ISSUE THREAD

**Issue by ogledylan1** [Palakis/obs-ndi#400] opened 2020-03-19 19:29 UTC
For some reason my MAC can't download the OBS NDI 4.7.1 software.... 
Mac software: macOS Catalina 10.15.3
OBS software: 24.0.6
The OBS link located on my toolbar on my Mac opens fine for when I go to download the OBS NDI 4.7.1 plug in my MAC its telling me [“obs-ndi-4.7.1-macOS.pkg” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.]
I don't really know how to take care of the problem idk if I need to download a different OBS NDI software but I could really use some help!

**Comment by Auto-moto-kyoto** [comment] 2020-03-23 15:52
I have the same issue exactly, i'm also on 10.15.3 and plug in 4.7.1 - I get the same warning.

**Comment by Palakis** [comment] 2020-03-24 14:35
Duplicate of #385

**Closed by Palakis** 2020-03-24 14:35 UTC

**Comment by BigEasy5** [comment] 2020-07-21 23:11
same problem and I went to system preferences-> security and privacy-> open anyway and the installation still failed
