### ISSUE TITLE
Not compatible with obs v28

### ISSUE THREAD

**Issue by flori-hei** [Palakis/obs-ndi#764] opened 2022-09-06 18:06 UTC
I just updated to the new obs version 28 and now when i start the pogram it says:

"following OBS-Plugins could not be loaded

obs-ndi

Please update or remove them"

I tryed it with an update to version 4.9 but it do not work. Is there a update planed? or do i have to use the old obs version?

This plugin in very important for me. If there is no update planed in near future i will go bach to OBS v27.

**Comment by MathDuck** [comment] 2022-09-06 20:58
The update is still in development. You can still test the alpha version located in here: https://github.com/Palakis/obs-ndi/actions/runs/2977380826

**Comment by Riotline** [comment] 2022-09-07 01:25
#745 Dupe

**Comment by SeiichiProd** [comment] 2022-09-07 05:02
> 

im not good at github, I follow the link but I have no idea how to download the alpha, what do I click? how do I do?

**Comment by Ron0x99** [comment] 2022-09-09 10:09
> The update is still in development. You can still test the alpha version for v28 located in here: https://github.com/Palakis/obs-ndi/actions/runs/2977380826

But how can I test the alpha version? I never know how to download/compile on Github.

**Comment by Riotline** [comment] 2022-09-09 10:11
@Ron0x99 at the bottom, you should see file links. You have to be signed in to download it

**Comment by Ron0x99** [comment] 2022-09-09 16:07
Ah thank you for pointing out that I have to be logged in xD That was the issue for me. I downloaded it and put the files in the OBS folders. But sadly my NDI sources are still saying "no properties available". Just have to wait until the latest version is completed.

**Comment by sunib** [comment] 2022-09-11 11:01
Thanks for already picking this up, I've downgraded OBS for now. Looking forward to the release.

**Comment by SurPaul** [comment] 2022-09-11 15:08
I'm waiting for the update too:
> No properties available

![image](https://user-images.githubusercontent.com/1708881/189534837-7f3a8525-5cf6-4050-b074-411fb352461c.png)

**Comment by mknooihuisen** [comment] 2022-09-11 23:41
> Ah thank you for pointing out that I have to be logged in xD That was the issue for me. I downloaded it and put the files in the OBS folders. But sadly my NDI sources are still saying "no properties available". Just have to wait until the latest version is completed.

I had that too, but if you recreate the source/filter using the alpha version shared in that link, it will work.  You can then just delete the old 4.9.1 versions (once you're sure you want to stay on 28)

**Comment by mknooihuisen** [comment] 2022-09-11 23:45
At first for me, it looked like the NDI Source was just missing from the add sources menu, but there will be a weird one called `Input.Name` that is actually the NDI source.  The property's names are also messed up, but you can figure it out from context, as long as you understand English.

Maybe they did not include the language localization files in the build, or perhaps I put them in the wrong spot.

**Comment by krystofkrticka** [comment] 2022-09-17 11:22
Duplicate of #745

**Comment by LixYt** [comment] 2022-09-18 20:57
Hi ! 

What's the best way to follow the progression of new version compatible with OBS 28+ ?

Should we contribute by testing Alpha/beta release ?

**Comment by Riotline** [comment] 2022-09-19 00:54
> What's the best way to follow the progression of new version compatible with OBS 28+ ?

You can follow #745 which is the original issue thread that is following the rewrite of the plugin.
This issue thread should be closed for being a duplicate as mentioned by numerous commenters.

**Comment by ki4swy** [comment] 2022-09-22 02:20
Confirmed the Alpha build works with 28.0.1 ( 64 Bit ) w/ NDI 5.0 , My Receiver is actually SLOBS 1.11..2 running NDI 4.0 and had no issues.

**Comment by JuanDagitab** [comment] 2022-09-23 07:03
This is my first time posting on GitHub. I apologize in advance if I posted my issue in the wrong thread.
The issue at hand is there appears to be a green tint on the program after I updated to OBS 28.0.2, which was prompted for me last night The sending OBS on the other hand is ok.
![vlcsnap-2022-09-23-15h02m29s826](https://user-images.githubusercontent.com/113210207/191907691-e737009f-5766-4772-a63e-c9cc88fbeb47.png)

**Comment by Chaniro** [comment] 2022-09-23 08:29
got the same issue with the green screen :(

**Comment by DrZeppers** [comment] 2022-09-24 01:22
I had that "green" issue with a few various chromakey filters in OBS28.
Had to redo a few various filters with the update, but had nothing to do with NDI.
Have you checked filters? Probably, but just thought id mention it.

**Comment by Chaniro** [comment] 2022-09-24 08:51
the issue is coming from OBS, and they are working on the hotfix

**Comment by JuanDagitab** [comment] 2022-09-24 08:55
> I had that "green" issue with a few various chromakey filters in OBS28. Had to redo a few various filters with the update, but had nothing to do with NDI. Have you checked filters? Probably, but just thought id mention it.

Thank you. Yeah, at first I thought it has something to do with some of my effects and filters and maybe overlays. However, I did check those and even started a new clean profile and scene collection in OBS. And yet it still persisted.

**Comment by JuanDagitab** [comment] 2022-09-24 08:56
> the issue is coming from OBS, and they are working on the hotfix

Thank you for the information. I guess we just have to wait for their fix.

**Comment by Chaniro** [comment] 2022-09-24 09:01
https://github.com/Palakis/obs-ndi/issues/745#issuecomment-1256726261

**Comment by leafac** [comment] 2022-09-24 12:48
For what it’s worth: I updated to OBS 28.0.2 & https://github.com/Palakis/obs-ndi/actions/runs/2977380826 and it’s working great. Awesome job @tt2468 and other people who are involved 😁 Thank you very much!

**Comment by tt2468** [comment] 2022-09-24 13:15
> This is my first time posting on GitHub. I apologize in advance if I posted my issue in the wrong thread. The issue at hand is there appears to be a green tint on the program after I updated to OBS 28.0.2, which was prompted for me last night The sending OBS on the other hand is ok. [EDIT] Everything was ok, at least according to what I'm seeing on my end up until OBS v28.0.1 ![vlcsnap-2022-09-23-15h02m29s826](https://user-images.githubusercontent.com/113210207/191907691-e737009f-5766-4772-a63e-c9cc88fbeb47.png)

This is believed to be an OBS bug which will be fixed in the next release.

**Comment by tt2468** [comment] 2022-09-24 13:15
Closing since this issue is a duplicate

**Closed by tt2468** 2022-09-24 13:15 UTC
