### ISSUE TITLE
Image tearing on frames from NDI Dedicated Output

### ISSUE THREAD

**Issue by gamespeaker** [Palakis/obs-ndi#41] opened 2017-08-20 15:42 UTC
Hello, thank you first of all for coming out with 4.1 so quickly.  I just tested it and I noticed that the ndi source seems to be tearing.  Kind of like interlacing.

Update....Does not do it if I use low bandwidth option selected.

**Comment by Palakis** [comment] 2017-08-20 17:24
What software/hardware is your NDI source? I've done some testing with VLC as the NDI source playing a tearing test video and can't reproduce. Maybe check your monitor and your GPU settings.

**Comment by gamespeaker** [comment] 2017-08-20 17:40
Sorry latest OBS studio On Windows 10, Using Logitech c910 webcam.

**Comment by Palakis** [comment] 2017-08-20 19:18
Maybe you mean the NDI filter a.k.a Dedicated NDI output? Because I can notice heavy tearing there.

**Comment by gamespeaker** [comment] 2017-08-20 19:32
Yes.   Am I doing it wrong ?

**Comment by Palakis** [comment] 2017-08-20 22:52
Not from what I can see. I can reproduce this issue on my end.

**Comment by gamespeaker** [comment] 2017-08-20 23:02
Hopefully easy fix.  Thank you again for looking at this.

**Comment by gamespeaker** [comment] 2017-08-24 18:46
Are there any updates to this issue yet?  Thank you

**Comment by Palakis** [comment] 2017-08-24 19:51
There's work underway on this but I have no idea why this happens.

**Comment by gamespeaker** [comment] 2017-08-26 11:48
Hello, I just installed 4.1.1 and same issues with image tearing for NDI Dedicated Output?
Is there a way to uninstall the plugin and re install?

**Comment by Palakis** [comment] 2017-09-01 18:07
> Is there a way to uninstall the plugin and re install?

Yes, standard uninstall procedure on Windows.

**Comment by gamespeaker** [comment] 2017-09-01 18:17
Hi
This plugin  has no uninstaller.  
Can we just delete the .dll?

**Comment by Palakis** [comment] 2017-09-01 18:17
Yup.

**Comment by gamespeaker** [comment] 2017-09-01 19:19
Ok, I just did that and reinstalled 4.1.1 tearing is still an issue.

**Comment by Palakis** [comment] 2017-09-01 23:05
> Ok, I just did that and reinstalled 4.1.1 tearing is still an issue.

I haven't said the opposite. I'm still working on fixing this.

**Comment by gamespeaker** [comment] 2017-09-02 00:05
Ah ok 😊. Love the plugin though.

**Comment by Palakis** [comment] 2017-09-07 16:01
Fixed in the latest commit to date.

**Closed by Palakis** 2017-09-07 16:02 UTC
Labels: bug
