### ISSUE TITLE
OBS-NDI not compatible with OBS 28.0.0, needs to target Qt6 instead of Qt5.

### ISSUE THREAD

**Issue by RAMChYLD** [Palakis/obs-ndi#759] opened 2022-09-02 01:42 UTC
So I was just upgraded to OBS 28.0.0. I keep getting segfaults and now it was pointed to me that this is because OBS has upgraded to Qt6 while OBS-NDI is still on Qt5. 

Can we fasttrack the rewrite?

**Comment by krystofkrticka** [comment] 2022-09-02 06:38
Duplicate of #745

**Closed** 2022-09-02 07:40 UTC
