### ISSUE TITLE
RegSvr32 failed with exit code 0x3

### ISSUE THREAD

**Issue by VexMex** [Palakis/obs-ndi#147] opened 2018-04-08 21:19 UTC
So i tried it now all

on my main computer, it works great, no problems at all

but then i have there my server
2 xeon E5620
24GB ram
Up-to-date windows
a more or elss working radeon hd 5450 that i never use since windows RDC

so i tried it with the .exe installer, and i tried it with zip and the seperate redist isntaller, booth dont want to install properly
after that i thought i miss the visual c++ stuff, installed all of them too, didnt work either (well all but 2017)
Also tried installing obs in the main directory, then onto my desktop, nothing changed, cant install it

if i would know how to properly edit the registry i would try that but i have no clue about that
it always stops while installing DirectShow\Filters.NdiSourceFilter.x86.dll

if additional informations are needed, imhappy to provide (but i ahve no logs since it doesnt let me install in the first palce)

**Comment by aaa4xu** [comment] 2018-06-05 14:26
Try install NDI Runtime first - works for me

**Comment by VexMex** [comment] 2018-06-05 17:50
well i did do that, atleast 10 times, and it didnt let me install it anyways

but with the ignore option it actually worked, even tho this is probably not intended

**Comment by Palakis** [comment] 2019-08-23 16:25
@VexMex doing some cleanup of the issues board and will close this. You can still comment here event if the issue is closed. If you still have that issue, try installing the latest version of OBS, the plugin and the NDI runtime.

**Closed by Palakis** 2019-08-23 16:25 UTC
Labels: incomplete
