### ISSUE TITLE
Ubuntu 19.10 obs-ndi.so install location

### ISSUE THREAD

**Issue by conradjones** [Palakis/obs-ndi#477] opened 2020-05-06 23:29 UTC
I installed OBS from the instructions on the OBS page for ubuntu :

`sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt install obs-studio`

I installed obs-ndi using the latest version  of the .debs from the releases section

OBS installed it is plugins in 

/usr/lib/obs-plugins/

obs ndi installed it's plugin in 

/usr/lib/x86_64-linux-gnu/

to fix this i had to create a symlink 

sudo ln -s /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/lib/obs-plugins/obs-ndi.so

**Comment by hasheddan** [comment] 2020-05-10 12:09
`sudo mv /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/lib/obs-plugins/.` works just fine as well :+1:

**Comment by conradjones** [comment] 2020-05-10 16:33
if you do the symlink you don't need to repeat it when you install an updated version of obs-ndi, if you mv the file then install an updated version in 6 months time you might not remember and still be using the old version because forgot to the do the mv again.

**Comment by hasheddan** [comment] 2020-05-11 00:36
@conradjones valid points :)

**Comment by Palakis** [comment] 2020-05-14 10:33
Duplicate of #461

**Closed by Palakis** 2020-05-14 10:33 UTC
Labels: bug
