### ISSUE TITLE
OBS NDI Sound scratch and quality

### ISSUE THREAD

**Issue by duestii** [Palakis/obs-ndi#802] opened 2022-12-09 00:06 UTC
Hello,

my video is absolut fine but my sound is scratching and bad quality is there any fixx for this ..? would appreciate <3

**Comment by Thorben0707** [comment] 2022-12-16 14:22
I have the same problem and its on the right side

**Comment by Trouffman** [comment] 2022-12-16 14:26
@Thorben0707 This has been solved, in a fork of this plugin : 
https://github.com/DDRBoxman/obs-ndi/releases/tag/4.10.1

Tested and approved.

**Comment by Thorben0707** [comment] 2022-12-16 14:33
> @Thorben0707 This has been solved, in a fork of this plugin : https://github.com/DDRBoxman/obs-ndi/releases/tag/4.10.1
> 
> Tested and approved.

I will test it, thank you

**Comment by Thorben0707** [comment] 2022-12-16 14:34
@Trouffman 
I will test it, thank you

**Comment by Thorben0707** [comment] 2022-12-16 14:52
@Trouffman Is it normal that the virus scanner deletes the file? :)

**Comment by Trouffman** [comment] 2022-12-16 17:27
@Thorben0707 it is NOT normal. And I do not have that problem on my side. (I only use the windows x64 zip version, not the installer)
If this problem persist, open a ticket on the other GitHub repo.

**Comment by CryptVicious** [comment] 2022-12-23 05:51
**Bad sound in right channel fix** The problem is two files were placed in the wrong spot. If you have crackling and static and it only goes away when you switch to the left channel...this fix will make it all go away and you will be good to use OBS 28. https://youtu.be/ldBE2Ndxlio
Or just take the files in this zip and replace their counterparts in the obs studio folder. I uninstalled everything OBS or NDI related first including in my app data folder but it would probably still work without doing that. after copying files, start OBS, a pop-up will appear asking you to install NDI runtime 5 or 5.5(can't remember) just say yes and when you reboot problem is gone. [obs-ndi-windows-x64-81a16120c (1) (1).zip](https://github.com/Palakis/obs-ndi/files/10266401/obs-ndi-windows-x64-81a16120c.1.1.zip)

**Comment by paulpv** [comment] 2023-02-28 01:03
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment] 2023-03-01 02:33
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.

**Closed by paulpv** 2023-03-01 02:33 UTC
