### ISSUE TITLE
Ndi Plugin is working one way but not the other.

### ISSUE THREAD

**Issue by BeaverG** [Palakis/obs-ndi#231] opened 2018-10-02 05:32 UTC
So, If I output ndi from my gaming pc to my streaming pc i get a stuttery mess of a preview.(but it works if i toggle the low bandwidth option.)  But if I output from my stream pc to my main pc i get a perfect preview... how does that makes any sense?

Main pc
i7 6700k 
16gb ram
gtx 970
240gb ssd
1 tb hd

Stream pc
Amd A8 6500
6 gb ram
1 tb hd

Please Help im new to this stuff and let me know if you need more info.

Gaming pc obs log

01:13:05.223: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
01:13:05.223: CPU Speed: 4008MHz
01:13:05.223: Physical Cores: 4, Logical Cores: 8
01:13:05.223: Physical Memory: 16308MB Total, 12785MB Free
01:13:05.223: Windows Version: 10.0 Build 17134 (revision: 286; 64-bit)
01:13:05.223: Running as administrator: false
01:13:05.223: Aero is Enabled (Aero is always on for windows 8 and above)
01:13:05.223: Windows 10 Gaming Features:
01:13:05.223: 	Game Bar: Off
01:13:05.223: 	Game DVR: Off
01:13:05.223: 	Game DVR Background Recording: Off
01:13:05.225: Sec. Software Status:
01:13:05.226: 	Avast Antivirus: enabled (AV)
01:13:05.227: 	Windows Defender Antivirus: disabled (AV)
01:13:05.227: 	Windows Firewall: enabled (FW)
01:13:05.227: 	Windows Defender Antivirus: disabled (ASW)
01:13:05.227: 	Avast Antivirus: enabled (ASW)
01:13:05.227: Browser Hardware Acceleration: true
01:13:05.227: Portable mode: false
01:13:05.302: OBS 22.0.2 (64-bit, windows)
01:13:05.302: ---------------------------------
01:13:05.314: ---------------------------------
01:13:05.314: audio settings reset:
01:13:05.314: 	samples per sec: 44100
01:13:05.314: 	speakers:        2
01:13:05.315: ---------------------------------
01:13:05.315: Initializing D3D11...
01:13:05.315: Available Video Adapters: 
01:13:05.316: 	Adapter 1: NVIDIA GeForce GTX 970
01:13:05.316: 	  Dedicated VRAM: 4239917056
01:13:05.316: 	  Shared VRAM:    4255227904
01:13:05.316: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
01:13:05.318: Loading up D3D11 on adapter NVIDIA GeForce GTX 970 (0)
01:13:05.360: D3D11 loaded successfully, feature level used: 45056
01:13:05.890: ---------------------------------
01:13:05.890: video settings reset:
01:13:05.890: 	base resolution:   1280x720
01:13:05.890: 	output resolution: 1280x720
01:13:05.890: 	downscale filter:  Lanczos
01:13:05.890: 	fps:               60/1
01:13:05.890: 	format:            NV12
01:13:05.890: 	YUV mode:          601/Partial
01:13:05.892: Audio monitoring device:
01:13:05.892: 	name: Default
01:13:05.892: 	id: default
01:13:05.892: ---------------------------------
01:13:05.893: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
01:13:05.894: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
01:13:05.929: [AMF] AMF Test failed due to one or more errors.
01:13:05.929: Failed to initialize module 'enc-amf.dll'
01:13:05.942: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
01:13:05.942: LoadLibrary failed for '../../obs-plugins/64bit/libEGL.dll': The specified procedure could not be found.
01:13:05.942:  (127)
01:13:05.942: Module '../../obs-plugins/64bit/libEGL.dll' not loaded
01:13:05.943: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
01:13:05.944: [obs-browser]: Version 2.1.5
01:13:05.947: NVENC supported
01:13:05.948: [obs-ndi] hello ! (version 4.5.2)
01:13:05.948: [obs-ndi] Trying 'C:\Program Files\NewTek\NewTek NDI 3.7 Redist\v3'
01:13:05.948: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NewTek NDI 3.7 Redist/v3/Processing.NDI.Lib.x64.dll'
01:13:05.952: [obs-ndi] NDI runtime loaded successfully
01:13:05.955: [obs-ndi] NDI library initialized successfully
01:13:05.964: [obs-ndi] starting NDI main output with name 'Beaver1'
01:13:05.968: [obs-ndi] 'Beaver1': ndi output started
01:13:05.998: Couldn't find VLC installation, VLC video source disabled
01:13:06.001: No blackmagic support
01:13:06.004: ---------------------------------
01:13:06.004:   Loaded Modules:
01:13:06.004:     win-wasapi.dll
01:13:06.004:     win-mf.dll
01:13:06.004:     win-dshow.dll
01:13:06.004:     win-decklink.dll
01:13:06.004:     win-capture.dll
01:13:06.004:     vlc-video.dll
01:13:06.004:     text-freetype2.dll
01:13:06.004:     rtmp-services.dll
01:13:06.004:     obs-x264.dll
01:13:06.004:     obs-vst.dll
01:13:06.004:     obs-transitions.dll
01:13:06.004:     obs-text.dll
01:13:06.004:     obs-qsv11.dll
01:13:06.004:     obs-outputs.dll
01:13:06.004:     obs-ndi.dll
01:13:06.004:     obs-filters.dll
01:13:06.004:     obs-ffmpeg.dll
01:13:06.004:     obs-browser.dll
01:13:06.004:     image-source.dll
01:13:06.004:     frontend-tools.dll
01:13:06.004:     enc-amf.dll
01:13:06.004:     coreaudio-encoder.dll
01:13:06.004: ---------------------------------
01:13:06.004: ==== Startup complete ===============================================
01:13:06.008: All scene data cleared
01:13:06.008: ------------------------------------------------
01:13:06.085: WASAPI: Device 'Speakers (Realtek High Definition Audio)' initialized
01:13:06.115: WASAPI: Device 'Microphone (4- ATR USB microphone)' initialized
01:13:06.163: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
01:13:06.462: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
01:13:06.606: ---------------------------------
01:13:06.606: [DShow Device: 'Video Capture Device'] settings updated: 
01:13:06.606: 	video device: Webcam C170
01:13:06.606: 	video path: \\?\usb#vid_046d&pid_082b&mi_00#6&1ee3204d&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
01:13:06.606: 	resolution: 640x480
01:13:06.606: 	fps: 30.00 (interval: 333333)
01:13:06.606: 	format: YUY2
01:13:06.677: [window-capture: 'Window Capture'] update settings:
01:13:06.677: 	executable: Europa_Client.exe
01:13:06.800: warning: deprecated pixel format used, make sure you did set range correctly
01:13:06.821: [window-capture: 'Window Capture 2'] update settings:
01:13:06.821: 	executable: League of Legends.exe
01:13:06.835: Switched to scene 'MAIN'
01:13:06.835: ------------------------------------------------
01:13:06.835: Loaded scenes:
01:13:06.835: - scene 'MAIN':
01:13:06.835:     - source: 'Window Capture' (window_capture)
01:13:06.835:     - source: 'Smash' (game_capture)
01:13:06.835:     - source: 'Game Capture' (game_capture)
01:13:06.835:     - source: 'Window Capture 2' (window_capture)
01:13:06.835:     - source: 'Flag' (image_source)
01:13:06.835:     - source: 'Beaver' (image_source)
01:13:06.835:     - source: 'Alert' (browser_source)
01:13:06.835:     - source: 'Sign' (image_source)
01:13:06.835:     - source: 'Total Followers' (text_gdiplus)
01:13:06.835:     - source: 'Viewer Count ' (browser_source)
01:13:06.835:     - source: 'Recent Follower' (text_gdiplus)
01:13:06.835:     - source: 'Top 10' (text_gdiplus)
01:13:06.835:     - source: 'Wins' (text_gdiplus)
01:13:06.835:     - source: 'Name' (text_gdiplus)
01:13:06.835:     - source: 'Video Capture Device' (dshow_input)
01:13:06.835:     - source: 'Border' (image_source)
01:13:06.835: - scene 'Big Cam':
01:13:06.835:     - source: 'Background' (image_source)
01:13:06.835:     - source: 'neon' (image_source)
01:13:06.835:     - source: 'Alert' (browser_source)
01:13:06.836:     - source: 'Recent follower' (text_gdiplus)
01:13:06.836:     - source: 'Total Followers' (text_gdiplus)
01:13:06.836:     - source: 'Chat' (browser_source)
01:13:06.836:     - source: 'Desktop' (monitor_capture)
01:13:06.836:     - source: 'BRB' (text_gdiplus)
01:13:06.836:     - source: 'Video Capture Device' (dshow_input)
01:13:06.836:     - source: 'Border' (image_source)
01:13:06.836: - scene 'Recording':
01:13:06.836:     - source: 'dgfhbvnb' (text_gdiplus)
01:13:06.836: ------------------------------------------------
01:13:06.933: CalculateFileHash: Failed to open file 'C:\Users\Beaver\AppData\Roaming\obs-studio\updates\whatsnew.json': 
01:13:12.257: [obs-ndi] stopping NDI main output
01:13:12.257: Output 'NDI Main Output': stopping
01:13:12.257: Output 'NDI Main Output': Total frames output: 373
01:13:12.257: Output 'NDI Main Output': Total drawn frames: 336 (377 attempted)
01:13:12.257: Output 'NDI Main Output': Number of lagged frames due to rendering lag/stalls: 41 (10.9%)
01:13:15.770: [obs-ndi] starting NDI main output with name 'Beaver1'
01:13:15.774: [obs-ndi] 'Beaver1': ndi output started
01:17:59.811: ==== Shutting down ==================================================
01:17:59.814: [obs-ndi] stopping NDI main output
01:17:59.814: Output 'NDI Main Output': stopping
01:17:59.814: Output 'NDI Main Output': Total frames output: 17039
01:17:59.814: Output 'NDI Main Output': Total drawn frames: 17043
01:17:59.858: Switched to scene '(null)'
01:18:00.129: WASAPI: Device 'Speakers (Realtek High Definition Audio)' Terminated
01:18:00.165: WASAPI: Device 'Microphone (4- ATR USB microphone)' Terminated
01:18:00.172: All scene data cleared
01:18:00.172: ------------------------------------------------
01:18:00.262: Freeing OBS context data
01:18:00.276: [obs-ndi] goodbye !
01:18:00.373: [Scripting] Total detached callbacks: 0
01:18:00.377: == Profiler Results =============================
01:18:00.377: run_program_init: 1958.63 ms
01:18:00.377:  ┣OBSApp::AppInit: 23.839 ms
01:18:00.377:  ┃ ┗OBSApp::InitLocale: 1.092 ms
01:18:00.377:  ┗OBSApp::OBSInit: 1882.88 ms
01:18:00.377:    ┣obs_startup: 4.086 ms
01:18:00.377:    ┗OBSBasic::OBSInit: 1618.59 ms
01:18:00.377:      ┣OBSBasic::InitBasicConfig: 0.621 ms
01:18:00.377:      ┣OBSBasic::ResetAudio: 0.164 ms
01:18:00.377:      ┣OBSBasic::ResetVideo: 577.057 ms
01:18:00.377:      ┣OBSBasic::InitOBSCallbacks: 0.005 ms
01:18:00.377:      ┣OBSBasic::InitHotkeys: 0.034 ms
01:18:00.377:      ┣obs_load_all_modules: 112.436 ms
01:18:00.377:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 0.458 ms
01:18:00.377:      ┃ ┣obs_init_module(enc-amf.dll): 34.148 ms
01:18:00.377:      ┃ ┣obs_init_module(frontend-tools.dll): 2.757 ms
01:18:00.377:      ┃ ┣obs_init_module(image-source.dll): 0.003 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-browser.dll): 0.247 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 0.701 ms
01:18:00.377:      ┃ ┃ ┗nvenc_check: 0.667 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-filters.dll): 0.01 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-ndi.dll): 19.887 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-outputs.dll): 0.005 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-qsv11.dll): 23.247 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-text.dll): 0.184 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-transitions.dll): 0.005 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-vst.dll): 0.001 ms
01:18:00.377:      ┃ ┣obs_init_module(obs-x264.dll): 0.001 ms
01:18:00.377:      ┃ ┣obs_init_module(rtmp-services.dll): 1.03 ms
01:18:00.377:      ┃ ┣obs_init_module(text-freetype2.dll): 0.127 ms
01:18:00.377:      ┃ ┣obs_init_module(vlc-video.dll): 0.033 ms
01:18:00.377:      ┃ ┣obs_init_module(win-capture.dll): 0.147 ms
01:18:00.377:      ┃ ┣obs_init_module(win-decklink.dll): 0.996 ms
01:18:00.377:      ┃ ┣obs_init_module(win-dshow.dll): 1.632 ms
01:18:00.377:      ┃ ┣obs_init_module(win-mf.dll): 0 ms
01:18:00.377:      ┃ ┣obs_init_module(win-wasapi.dll): 0.004 ms
01:18:00.377:      ┃ ┗reset_win32_symbol_paths: 0.063 ms
01:18:00.377:      ┣OBSBasic::ResetOutputs: 0.445 ms
01:18:00.377:      ┣OBSBasic::CreateHotkeys: 0.028 ms
01:18:00.377:      ┣OBSBasic::InitService: 1.034 ms
01:18:00.377:      ┣OBSBasic::InitPrimitives: 0.188 ms
01:18:00.377:      ┗OBSBasic::Load: 855.685 ms
01:18:00.377: obs_hotkey_thread(25 ms): min=0.003 ms, median=0.022 ms, max=4.865 ms, 99th percentile=0.085 ms, 100% below 25 ms
01:18:00.377: audio_thread(Audio): min=0 ms, median=0.072 ms, max=1.316 ms, 99th percentile=0.219 ms
01:18:00.377: obs_graphics_thread(16.6667 ms): min=0.066 ms, median=1.783 ms, max=711.85 ms, 99th percentile=6.096 ms, 99.983% below 16.667 ms
01:18:00.377:  ┣tick_sources: min=0.002 ms, median=1.295 ms, max=710.038 ms, 99th percentile=5.152 ms
01:18:00.377:  ┣output_frame: min=0.055 ms, median=0.379 ms, max=1.808 ms, 99th percentile=0.767 ms
01:18:00.377:  ┃ ┣gs_context(video->graphics): min=0.054 ms, median=0.222 ms, max=0.872 ms, 99th percentile=0.489 ms
01:18:00.377:  ┃ ┃ ┣render_video: min=0.005 ms, median=0.08 ms, max=0.59 ms, 99th percentile=0.195 ms
01:18:00.377:  ┃ ┃ ┃ ┣render_main_texture: min=0.003 ms, median=0.051 ms, max=0.546 ms, 99th percentile=0.121 ms
01:18:00.377:  ┃ ┃ ┃ ┣render_output_texture: min=0.001 ms, median=0.008 ms, max=0.141 ms, 99th percentile=0.025 ms
01:18:00.377:  ┃ ┃ ┃ ┣render_convert_texture: min=0.001 ms, median=0.01 ms, max=0.186 ms, 99th percentile=0.027 ms
01:18:00.377:  ┃ ┃ ┃ ┗stage_output_texture: min=0 ms, median=0.008 ms, max=0.265 ms, 99th percentile=0.028 ms
01:18:00.377:  ┃ ┃ ┣gs_flush: min=0.024 ms, median=0.061 ms, max=0.439 ms, 99th percentile=0.225 ms
01:18:00.378:  ┃ ┃ ┗download_frame: min=0 ms, median=0.075 ms, max=0.499 ms, 99th percentile=0.203 ms
01:18:00.378:  ┃ ┗output_video_data: min=0.11 ms, median=0.146 ms, max=1.592 ms, 99th percentile=0.307 ms
01:18:00.378:  ┗render_displays: min=0 ms, median=0.122 ms, max=2.407 ms, 99th percentile=0.329 ms
01:18:00.378: video_thread(video): min=1.267 ms, median=1.997 ms, max=68.353 ms, 99th percentile=5.389 ms
01:18:00.378: =================================================
01:18:00.378: == Profiler Time Between Calls ==================
01:18:00.378: obs_hotkey_thread(25 ms): min=25.003 ms, median=25.931 ms, max=29.916 ms, 0.0966948% within ±2% of 25 ms (0% lower, 99.9033% higher)
01:18:00.378: obs_graphics_thread(16.6667 ms): min=1.666 ms, median=16.667 ms, max=711.86 ms, 99.8751% within ±2% of 16.667 ms (0.0681083% lower, 0.0567569% higher)
01:18:00.378: =================================================
01:18:00.428: Number of memory leaks: 0

**Comment by baircave** [comment] 2018-10-08 19:39
I'm having this issue as well... it's strange because when I first set it up last week it was having no issues going the other way but now my stream PC won't receive anything other than a stuttery mess like @BeaverG is describing. Audio appears to be coming through with no issues though.

**Comment by Palakis** [comment] 2020-03-24 13:43
Duplicate of #62

**Closed by Palakis** 2020-03-24 13:43 UTC
Labels: black-screen, duplicate, network-interference
