### ISSUE TITLE
Cann't mute Sound

### ISSUE THREAD

**Issue by DeathmannX** [Palakis/obs-ndi#267] opened 2019-01-26 17:11 UTC
Hi there i'am try to use my Streamdeck to turn my Mic on and off, but i use the NDI Sound Filter on those Devices so it looks like i cann't turn the Devices on and off without any Effects for the Stream.

If i don't use the Filters on my Gaming PC i get stuttering Sounds on my Streaming PC...
Any Idea or fix for that?

**Comment by ThatGirlSlays** [comment] 2019-01-27 11:00
I'm confused about what you are asking so I want to rephrase and you can let me know if this is what you are talking about.

I think I am having a similar issue that you described. On my gaming PC I have the option to either send all audio sources out with the Main NDI Output OR I can add the "Dedicated NDI Output (audio only)" filter to each audio source. On my streaming PC, I would see one channel that would have all of my audio channels combined into one (this is a result of the Main NDI Output channel) as well as a separate NDI source/channel for each audio source I applied the filter to. When I tried using my stream deck to mute/unmute my mic, it would affect my gaming computer, the combine Main NDI Output audio channel on the streaming PC but NOT the individual/separate mic NDI source on my streaming PC.

I think that is the same issue you are having but unfortunately I don't think there is a solution other than to  grab another stream deck or macro controller for your streaming PC.

Unfortunately for me, the audio stuttering is persistent no matter which option I use.

**Comment by DeathmannX** [comment] 2019-02-02 20:02
Any real Solution by the Devolpers?@Palakis

**Comment by Palakis** [comment] 2020-03-24 13:59
Duplicate of #138

**Closed** 2020-03-24 13:59 UTC
Labels: duplicate
