### ISSUE TITLE
Upgrade to NDI SDK v3

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-ndi#37] opened 2017-08-16 21:21 UTC
NDI SDK v3 has just been released with some noteworthy features. From the email:

> - Full backwards (NDI® v3 interoperates with all previous versions) and forwards compatibility (previous versions all work with NDI® v3).
> - Full multicast support with forwards error correction. NDI® is now able to use both unicast and/or multicast in order to achieve the best possible performance.
> - Support for hardware devices from both NewTek and other manufacturers with more coming soon. This includes a new “high efficiency mode” (NDI®|HX) suitable for low bandwidth and wireless networks.
> - Standardized control of PTZ cameras, recording devices and user interfaces.
> - High precision time-stamps that allow synchronization between streams, video sources, including different computers that are running with accurately locked clocks.
> - And as always, there are a huge number of other improvements including performance: hardware accelerated decoding, new meta-data capabilities, better tools and utilities, and much more.

The hardware accelerated decoding and high efficiency (HX) mode are of particular interest to me.

**Comment by Palakis** [comment] 2017-08-17 08:46
Yeah I got that email too. That's awesome news!
I'll have a look at this this weekend.

**Comment by Palakis** [comment] 2017-08-17 09:47
Among the new features:
>USER INTERFACE SUPPORT
Applications may access and provide embedded user interfaces using web controls over NDI. When a
connection is made to a sender, an embedded web URL can be provided. This can serve to allow a
down-stream application to provide a control application via a web interface on demand.

Holy shit.

**Comment by Palakis** [comment] 2017-08-17 10:06
> Holy shit

Nevermind, that's just a way for a sender to provide a URL to an embedded web interface.

**Comment by Palakis** [comment] 2017-08-17 10:07
Most of these improvements are transparent to the user. But reading from the docs, NDI-HX sender implementations are only available on demand, though. I believe SDKv3 supports receiving NDI-HX sources anyway.

**Comment by mr-teatime** [comment] 2017-08-17 16:53
Hey im personally interested in ndi-HX myself (mostly because I ran headfirst into a wall with video quality namely anything over 4k30p just chugs along when its decoding, whereas if i use vmix 20.0 preview (which uses ndi3.0) and output that same 4k60p source it runs fine (its still using 20% cpu to decode the stream but its not decoding at like 5 fps like if obs is the source)

**Comment by matiaspl** [comment] 2017-08-17 20:10
I don't think it's v2 vs v3. NDI is sort of an mpeg-2, so not a single
modern PC should have a problem decoding a 4Kp60 stream. I guess there's a
problem with internal buffer throughput. I.e. ffmpeg advanced filtering
pipeline used to have problems (I'm not sure it still does) with realtime
processing of 4Kp25 and more, unless you used fifos in between the filters.

Matt


17.08.2017 18:53 "mr-teatime" <notifications@github.com> napisał(a):

Hey im personally interested in ndi-HX myself (mostly because I ran
headfirst into a wall with video quality namely anything over 4k30p just
chugs along when its decoding, whereas if i use vmix 20.0 preview (which
uses ndi3.0) and output that same 4k60p source it runs fine (its still
using 20% cpu to decode the stream but its not decoding at like 5 fps like
if obs is the source)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Palakis/obs-ndi/issues/37#issuecomment-323131387>, or mute
the thread

**Comment by mr-teatime** [comment] 2017-08-17 20:45
Nah its behaving more like an overloaded encoder, namely it only starts to behave that way at 4k60 and only when obs is one the streaming the ndi.

If vmix streams the ndi it can do 4k60 just fine, the difference between the two besides the host program is the codec used (vmix uses the ndiv3.0 version of speedhq and this plugin uses the ndi2.0 version of speedhq)

Im starting to think that my best solution would be to create my own plugin and just send raw bmp's with a timestamp as im working in an environment with the bandwidth to support such an implementation (and this would mean absolutely no work is done compressing or decompressing the frames)

**Comment by Palakis** [comment] 2017-08-17 21:01
I started working on the update to NDI 3.0. See internal PR here: https://github.com/Palakis/obs-ndi/pull/38

**Comment by matiaspl** [comment] 2017-08-17 21:11
The encoder might be starving as well. Copying 60 32-bit 4K uncompressed
bitmaps per second takes a lot of bandwidth. If there's no double buffering
on the filter input, we might be loosing frames there. Is your CPU getting
saturated?

Matt

17.08.2017 22:45 "mr-teatime" <notifications@github.com> napisał(a):

**Comment by mr-teatime** [comment] 2017-08-17 21:14
Yeah i saw you working on it earlier while i was looking for the files id need to compile my own version with the updated dll's.

Never did get the compile to work (namely i seem to be missing the obs.lib, obs-frontendapi.lib a few cmake files and some qt5 files) so im basically just going to have to wait patiently for some precompiled binaries.

Im going to make a huge assumption here and assume youve already started testing, have you seen any performance increase so far in comparison to 2.0?

**Comment by Palakis** [comment] 2017-08-17 22:05
@mr-teatime Just commented the PR with link to binary builds.

**Comment by mr-teatime** [comment] 2017-08-17 22:22
@palakis thats just the source code isnt it? i cant compile it because im missing some files for some reason (files that the obs source and your sources both dont provide)

**Comment by mr-teatime** [comment] 2017-08-17 22:42
Alright done some more testing, the breakpoint is exactly 4k50

it starts to skip a couple frames at 48 fps but at 50fps the program will crash when turning off ndi every time, and the frame skipping is very noticible.

from 50-60 it gets progressively choppier very rapidly till you reach sub 1fps at 60fps.

That is exactly 414.72 megabits of bitrate, i dont know how big the buffer is in obs but im going to assume thats too big for it haha.

**Comment by Palakis** [comment] 2017-08-17 22:43
@mr-teatime No, those are compiled binary builds.

**Comment by Palakis** [comment] 2017-08-17 22:43
> Alright done some more testing, the breakpoint is exactly 4k50

What are you talking about? Which version of obs-ndi are you using?

**Comment by mr-teatime** [comment] 2017-08-17 22:53
@palakis The 3.0 test binaries, its the same problem as the 2.0 ones, although i may have to make a new issues thread for it, i initially thought it was a result of the 2.0 codec not being able to handle 4k60 but i just figured out its the buffer being too small.

Tested a x.264 stream where i made the buffer smaller than the bitrate and it behaved identically to the issue im having.

Im not sure if you are setting a buffer for the ndi output or if its an obs issue though, if you are setting a buffer for the ndi output in the code consider this a formal request to allow us to set our own buffer haha.

**Comment by Palakis** [comment] 2017-08-17 22:57
@mr-teatime I can notice slight choppiness in the Video Monitor at 1080p60, but OBS stats show nothing wrong with the NDI output. If an issue is happening, it's within the NDI library.

**Comment by mr-teatime** [comment] 2017-08-17 23:01
My issue is with 4k resolutions.

At 4k you start to notice choppiness around 50 frames per second, and you get an unhandled exception e06d7363 when turning off ndi at above 4k50p output

at 4k60 the frames only update once every few seconds.

the fact that it gets worse the faster you try to push it leads me to believe the buffer is full so its skipping frames in an attempt to catch up.

**Comment by Palakis** [comment] 2017-08-17 23:02
@mr-teatime Nevermind, that choppiness happens only in Video Monitor. I don't see it when receiving OBS into another OBS.

**Comment by mr-teatime** [comment] 2017-08-17 23:04
I mean it has to be obs or the plugin since vmix is doing 4k60 fps with no trouble whatsoever and its using ndi3.0 aswell.

One of the two is crapping itself at 414.72 megabits

**Comment by mr-teatime** [comment] 2017-08-18 00:22
Ok yeah can confirm its the buffer now, if i let it sit on a still frame for a few minutes without changing the frame so the encoder can catch up my cursor moves normally around the output (because the cursor isnt changing enough pixels to warrant rendering the entire frame again)

If i then add motion back to the frame so it has to rerender the whole thing it streams smoothly for about 4 seconds before it goes back to a frame skipping mess.

As for why it gets worse the longer you play it, id have to assume that because its rendering frames asynchronously its just sending more calls for frames to be rendered despite the fact the first call to render never finished so the frames take longer and longer to render causing more calls simultanious frame rendering causing longer frames etc etc in a downward spiral, this would also be why the frame skips get larger as you increase the bitrate because it can render less frames before the buffer gets bogged down leading to the async downward spiral.

**Comment by Palakis** [comment] 2017-08-18 17:36
I'm gonna close this, as NDI 3.0 has been integrated into obs-ndi.
Regarding the global performance of obs-ndi, I've experiments in 2160p60 and identified a huge bottleneck in the NDI main output, caused by the explicit pixel format conversion going through libswscale.
Since I can't really have a proper smooth 4K using the NDI plugin for VLC, it's a bit harder to troubleshoot that area.

**Comment by Palakis** [comment] 2017-08-18 17:37
@mr-teatime Feel free to open another issue dedicated to 4K performance issues, with detailed pipeline/workflow details. Fixing issues with 4K with also fix minor issues with HD in the process.

**Closed by Palakis** 2017-08-18 17:37 UTC

**Comment by Palakis** [comment] 2017-08-20 15:09
[obs-ndi 4.1.0 has been released](https://github.com/Palakis/obs-ndi/releases/tag/4.1.0), which has been updated to use NDI 3.0.
