### ISSUE TITLE
muting desktop audio on Gaming PC doesn't mute it on Stream PC

### ISSUE THREAD

**Issue by D0jii** [Palakis/obs-ndi#158] opened 2018-05-02 05:23 UTC
When I mute 'desktop audio' in mixer on OBS -- the meter stops moving.  When I look on the Gaming pc OBS the meter is moving.  Somehow the mixer muting 'interfacing' isn't carrying over NDI plugin to the Streaming unit.

Muting microphone device in mixer works.  Have reinstalled obs studio, and ndi plugin on both machines and checked to make sure I was on the latest version.  Have checked to make sure my default audio devices are consistent with obs settings.  

Somehow the mixer is muting but when the signal is sent over NDI to the stream pc -- it doesn't detect that the desktop audio device is muted.  

It may be related to my microphone being also used as a sound card?  I have the at2020 usb condenser microphone.  I know nothing about coding but I am feeling confident with being able to troubleshoot, build pcs, and maintain a high quality stream.  not sure if this is the right place to report this issue, the website seems geared towards people who do all the 10010110110110111 magic.  but yea... any suggestions?

**Comment by Palakis** [comment] 2018-07-06 12:43
@D0jii 
>  Somehow the mixer muting 'interfacing' isn't carrying over NDI plugin to the Streaming unit.

Are you using the Main Output or a Dedicated Output filter?

**Comment by D0jii** [comment] 2019-03-27 23:45
I'm using Dedicated output now.  on my audio tracks to remove desync issues.  but mute doesn't carry over.

**Comment by StephenMP** [comment] 2019-04-01 19:28
Just wanting to note, @Palakis this is still an issue. If the audio source is muted in OBS, the NDI Dedicated Output (audio only) filter still sends the audio over NDI to the streaming PC :(

**Comment by D0jii** [comment] 2019-04-08 03:20
is there any work around for this?  I pretty much don't interact with the stream PC obs at all when i'm streaming.   Not sure why but my mic audio desyncs, usually only when I encode really graphically intense games.  (encoding on stream pc with 16 core threadripper though).    Sync is set to internal.   Should I use hardware acceleration?  

If I can fix the sync issue I really won't have to use a dedicated output filter for the mic audio.

**Comment by loopy750** [comment] 2019-04-08 09:24
> usually only when I encode really graphically intense games

This part kinda pricked my ears. As a test, if you're interested in trying to reproduce this on demand, I have a "stress test" image I made that you can try and see if the intensity, so-to-speak, is enough to cause instant desync. https://i.ibb.co/LhrTNWc/1.png

**Comment by StephenMP** [comment] 2019-04-08 15:10
@D0jii my workaround may not work for you since I run two Stream Decks (one plugged into my gaming rig and one into my streaming rig). So I just set my streaming rig Stream Deck to have actions that Activate and Deactivate the proper NDI source for the audio I want to mute/unmute.

I'm unfamiliar with the OBS API, so I'm not sure if there is a way to check the mixer first to see if the audio source is muted prior to sending the audio data to the NDI API.

![image](https://user-images.githubusercontent.com/1134278/55735182-16b3ba80-59de-11e9-94b4-5529cba2475a.png)

**Comment by rdomingue** [comment] 2019-04-19 04:28
I have the same issues. There is no development on this ?.
In fact I've try disable the filter and the main NDI output still send audio even if the mic/aux is muted.
I'm using the push-to-mute feature of OBS to mute myself on the gaming pc the mic is muted and the graph doesn't raise up but on the streaming PC I have sound coming in. IF I click the little speaker icon to disable (or mute) the mic/aux now there is no sound coming in the streaming pc. 

With the NDI audio dedicated output with the push-to-mute or even with the white speaker icon the sound goes through the streaming pc.

**Comment by StephenMP** [comment] 2019-04-22 06:31
@rdomingue 
The reason the mute doesn't work is because it seems that OBS still runs your audio through all the filters before determining that the audio is muted, then blocking the final audio output after all the filters. Because of this, the audio still hits the dedicated NDI output filter which sends the output through NDI as part of the filter functionality (as shown in the code screenshot above).

**Comment by macb** [comment] 2019-08-08 22:36
It's still extremely unexpected behavior. Is there an open OBS issue for addressing that? Or is there a planned workaround for obs-ndi?

**Comment by rdomingue** [comment] 2019-08-08 22:40
I guess it’s more than a feature but as @macb said it’s the expected behaviour ... but anyway as soon as it’s fix it will be perfect ;-)

**Comment by JaySNL** [comment] 2019-08-30 16:03
If this is still a required workaround, use: https://obsproject.com/forum/resources/command-line-tool-for-obs-websocket-plugin-windows.615/

![SOGND3](https://user-images.githubusercontent.com/7669379/64035128-4d869a80-cb50-11e9-8a17-4794331246e0.png)

On main pc add two audio sources to toggle local mute/unmute, add a "system open" event on streamdeck. Add shortcut to file like so:
x:\[location to files]\OBSCommand_1.4.3\OBSCommand\OBSCommand.exe /server=yourstreamrigip:4444 /toggleaudio="audio source"

This will mute and un-mute audio sources locally AND on remote rig. Repeat where necessary.

**Comment by Palakis** [comment] 2020-03-24 13:30
Duplicate of #138, should be address in version 4.8.0

**Closed by Palakis** 2020-03-24 13:30 UTC
Labels: duplicate, feature

**Comment by OGNetheri** [comment] 2022-08-07 11:58
This issue is still alive and kicking, just noticed it today when I was about to kick stream on. There's no muting happening when it's done on gaming PC. Therefore also when the scene is changed, audio sources keep going through to streamPC even when they aren't in the scene used in OBS.
