### ISSUE TITLE
Output Height broken?

### ISSUE THREAD

**Issue by AxyxDeveloper** [Palakis/obs-ndi#431] opened 2020-04-08 15:25 UTC
https://github.com/Palakis/obs-ndi/issues/373

I have the same as here :(

**Comment by Palakis** [comment] 2020-04-08 15:29
@AxyxDeveloper This is fixed and will be released in obs-ndi 4.8.0

**Comment by Palakis** [comment] 2020-04-08 15:29
Duplicate of #373

**Closed by Palakis** 2020-04-08 15:29 UTC

**Comment by AxyxDeveloper** [comment] 2020-04-08 15:31
it isnt fixed for me

**Comment by AxyxDeveloper** [comment] 2020-04-08 15:32
it worked on my second device but not on my main

**Comment by dodgepong** [comment] 2020-04-08 15:54
obs-ndi 4.8.0 isn't released yet. Wait for the release and update when it is available, then it will be fixed.

**Comment by AxyxDeveloper** [comment] 2020-04-08 15:57
i fixed it with reinstalling but i still get blackscreen and my firewall is set
