### ISSUE TITLE
Obs NDI 4.7.1

### ISSUE THREAD

**Issue by seanstreet** [Palakis/obs-ndi#433] opened 2020-04-10 05:33 UTC
When I download the file and try to install it, I get the message in the image.
![Screen Shot 2020-04-10 at 3 29 49 pm](https://user-images.githubusercontent.com/63440794/78965492-8eac4780-7b40-11ea-8653-514ccc69f40c.png)

**Comment by Palakis** [comment] 2020-04-10 07:40
@seanstreet Go into Preferences > Security & Privacy, and click on Open Anyway

**Comment by Palakis** [comment] 2020-04-10 07:40
Duplicate of #385

**Closed by Palakis** 2020-04-10 07:40 UTC
