### ISSUE TITLE
CPU usupported by NDI library. Module won't load.

### ISSUE THREAD

**Issue by Qranequinn** [Palakis/obs-ndi#44] opened 2017-08-25 21:40 UTC
This is it pretty much. Got it in log file, was looking at it out of desperation.
AMD Athlon II X2 215. The bug or have I gotten just a shitty hardware?

**Comment by Palakis** [comment] 2017-08-25 21:57
Duplicate of #33. Please contribute to the discussion there.

**Closed by Palakis** 2017-08-25 21:58 UTC

**Comment by Palakis** [comment] 2017-08-25 21:59
Also, please try the binary provided as a comment in #33 to see if the plugin loads properly. And report success or failure in that thread, not here.
