### ISSUE TITLE
NDI Source menu shows Skype sources, but only red box appears

### ISSUE THREAD

**Issue by peterhassett** [Palakis/obs-ndi#344] opened 2019-09-15 01:58 UTC
Windows PC
OBS 23.2.1
Running latest NDI and NDI runtime

1. start OBS
2. start skype call
3. In OBS add NDI source
4. See callers in dropdown list
5. Choose item
6. See red square at top left of screen
7. Video of source does not appear

![red square](https://user-images.githubusercontent.com/8505967/64915682-c124cc00-d73a-11e9-8fca-01dcb94b153b.png)

I've tried restarts, uninstalls, etc.

**Comment by olegchir** [comment] 2019-09-27 18:00
the same for me

**Comment by mattlangan** [comment] 2019-11-01 22:19
Same here. I have tried uninstalling and reinstalling everything (obs-ndi, obs studio, ndi 4, ndi tools, etc..) but nothing seems to work. I am attempting this with OBS Studio 24.0.3, OBS-NDI 4.7, Skype 8.53.0.85, and Windows 10.

**Comment by Palakis** [comment] 2020-03-24 14:13
Duplicate of #62

**Closed** 2020-03-24 14:12 UTC
Labels: black-screen, duplicate
