### ISSUE TITLE
OBS Ndi black screen problem (I think it's a firewall issue)

### ISSUE THREAD

**Issue by paolomcbrain** [Palakis/obs-ndi#273] opened 2019-02-13 00:23 UTC
I'm having issues with the OBS in the laptop which receives the signal, it shows me a black screen. I think the problem is on the firewall of the laptop because I set the firewall to allow OBS to work on the private network and it worked until I turned off the laptop and turned it on the next day. The laptop's OBS recognizes the streaming PC signal but it doesn't show any image.

Both computers are connected by a switch gigabyte LAN and the Ethernet cables are CAT6 and I'm using the latest versions of both OBS and Ndi.

I made a test in which the laptop sent the image to my streaming PC and it worked perfectly, that's why I think the problem is on the firewall.

Thanks.

**Comment by aj123gamer** [comment] 2019-07-14 16:48
Hi. I'm facing the exact same issue. The thing is, I have to disable the firewall completely to allow the NDI work. With the Firewall activated, I only see black screen. Once, I turn off the firewall, I get the screen.

**Comment by Palakis** [comment] 2020-03-24 14:00
Duplicate of #62

**Closed by Palakis** 2020-03-24 14:00 UTC
Labels: black-screen, duplicate
