### ISSUE TITLE
Streaming Laptop blackscreen

### ISSUE THREAD

**Issue by Banbeucmas** [Palakis/obs-ndi#167] opened 2018-06-01 15:14 UTC
This had been happening pretty often to me since the first day I sue NDI.
I am using Linux Ubuntu 16.04 LTS as my Streaming PC and Window 8.1 for my Gaming PC.
This happening on all of the ndi version I gone throught but I am using the lastest right now just to be sure.

So, It always takes me about 30m - 1 hour of resetting everything for the Streaming PC to capture.
In case you don't know, here is my OBS setting when I add a new source on the streaming PC
![image](https://user-images.githubusercontent.com/10562127/40847847-71c31176-65f8-11e8-9070-254e39fc31cc.png)
And my Gaming PC
![image](https://user-images.githubusercontent.com/10562127/40847873-7dd73744-65f8-11e8-8bfa-c49feb9f8567.png)

Now, what really interesting is that while the Streaming PC did find the Gaming PC, it showed a black screen to me. 
Both of the laptop are connected through a Router, a TPLink TL-WR940N

Second thing, I got all of my Network Adapter disabled on my Gaming PC when I set up the stream.

![image](https://user-images.githubusercontent.com/10562127/40847992-d7043fa6-65f8-11e8-9682-7ea7389fdc02.png)

Now, what really interesting is that by seeing through Task Manager on my gaming PC, OBS didn't sent any packet whatsoever.
![image](https://user-images.githubusercontent.com/10562127/40848055-06ae935a-65f9-11e8-9ff4-50ab476c9b67.png)

I also have a WireShark data file which is proving this to be true I assume.

https://drive.google.com/file/d/1sAt39JwC23ndxlV0aWIAKH2b31S2qqS1/view?usp=sharing

Even it is short, but that's it. No more interesting data showed up when I put this on 1 hour  (And forgot to save it)
I had tried every possible sync setting and the result are all the same. Sometime it randomly worked for no reason.
There need to be a solution for this, may be find a way to trigger the NDI source to fire up some packet to a targeting pc?

**Comment by Banbeucmas** [comment] 2018-06-22 11:17
Bump, anyone?

**Comment by Palakis** [comment] 2020-03-24 13:34
I'm doing a bit of triaging and I'll be closing this, as it's a duplicate of #62.

**Closed by Palakis** 2020-03-24 13:34 UTC
Labels: black-screen, duplicate, no-signal, video
