### ISSUE TITLE
OBS doesn't close properly . Leaving an instance in Task Manager that required manually "END TASK" to close. 

### ISSUE THREAD

**Issue by ottawafro** [Palakis/obs-ndi#338] opened 2019-08-28 17:48 UTC
Basically I don't want to use this for PC to PC ... although I can get that to work on my gaming PC ( wireless ac ) and an old PC ( wired ) into router... Did also test having gaming PC wired to Router ... I just want to be able to import Skype calls... wish they was a way only to add the NDI Source and not the rest of it ... 

My issue is that my usage goes from 6 - 8 % to about 18% - 20%. which I am not sure if this is normal performance for the plugin.... 

![Obs_CPU_Usage](https://user-images.githubusercontent.com/54640567/63879713-40c04600-c99a-11e9-9444-661bd7724e0a.PNG)

Also after closing OBS , there is still an instance of it running in the background. I always have to go into Task Manager to close it. This happens on both PCs... Do anyone else have this is or had this issue ? 

![Obs_CPU_Usage_task_manager](https://user-images.githubusercontent.com/54640567/63879714-40c04600-c99a-11e9-9686-33fc50ec4a25.PNG)

If i uninstall the NDI plugin... 

PC usage back to normal . ( 6.1% in screenshot ) 

![Obs_CPU_Usage_withoutNDI](https://user-images.githubusercontent.com/54640567/63879715-40c04600-c99a-11e9-8469-c218a76ceb4d.PNG)

Closing the program doesn't leave anything open in Task Manager... 

Here some information from the log; 

13:15:09.349: CPU Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
13:15:09.349: CPU Speed: 2808MHz
13:15:09.349: Physical Cores: 4, Logical Cores: 8
13:15:09.349: Physical Memory: 32652MB Total, 27925MB Free
13:15:09.349: Windows Version: 10.0 Build 17763 (revision: 678; 64-bit)

Please help ... been trying to figure if I doing something wrong, something with my set up ... At my wits end... 

For now , not installing the PLUGIN , unless I have a skype call planned .... Not worth the extra PC usage for what I would do ... would like to have the PLUGIN installed if can get these issues resolved ( especially the 2nd one )

**Comment by ottawafro** [comment] 2019-09-20 08:01
Seems to be resolved with new NDI .... just updated the plugin and still no issues. Will continue to monitor. But now when I close OBS , it actually closes with the NDI plugin installed.

**Comment by orbanbalage** [comment] 2021-04-23 15:07
I've noticed the same symptoms under different specs:

OBS: 25.0.8 + obs-ndi: 4.7.1 => no issue
OBS: 26.1.1 + obs-ndi: 4.7.1 => background process remains
OBS: 27.0.rc1 + obs-ndi: 4.7.1 => background process remains

(maybe it's caused by a different problem with the newer OBS...)

I will post the results of OBS: 25 + obs-ndi: 4.9.1 build combo later.

**Comment by orbanbalage** [comment] 2021-05-03 18:14
OBS: 25 + obs-ndi: 4.9.1_c7badde => no issue!

**Comment by paulpv** [comment] 2023-03-01 03:38
This seems fixed in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC; Closing.
Feel free to comment if you test and disagree and I should reopen.

**Closed by paulpv** 2023-03-01 03:38 UTC
Labels: bug, needs-investigation
