### ISSUE TITLE
NDI plugin is not working in Obs

### ISSUE THREAD

**Issue by Masihanurag** [Palakis/obs-ndi#765] opened 2022-09-14 05:17 UTC
Respected NDI team service,

When i'm downloading this plugin i'm seeing this problem with option.

**(obs-ndi-4.9.0 -win....exe is not commonly downloaded and may be dangerous)**

After the download is completed and after the installation, when i open the OBS, i see this option.

**(The following OBS plugins failed to load:
obs-ndi
please update or remove these plugins)

Kindly solve this issues quickly and provide me its solution.**

Regards,
Anurag Masih

**Comment by Akashic101** [comment] 2022-09-14 06:29
Dupe of #745, the update is still in development. You can still test the alpha version for v28 located in here: https://github.com/Palakis/obs-ndi/actions/runs/2977380826

**Comment by Masihanurag** [comment] 2022-09-14 09:57
Dear Sir,

I just downloaded the alpha version for window and pasted it in the Plugin part of OBS, but now when I'm opening the OBS, this type of message is showing **(plugin Load. LibError. Message, Window)**

sir this is very importation for me because in sunday church service I will need NDI plugin to display bible verses in live stream on YouTube platform .

**Comment by Masihanurag** [comment] 2022-09-14 10:04
![Capture](https://user-images.githubusercontent.com/113496520/190125386-15adb359-fd9b-43e7-b2a0-76a9f5f9e724.PNG)

**Comment by Akashic101** [comment] 2022-09-14 10:25
If this is for whatever reason not working for you I would suggest two alternatives:

1: Use this NDI-Alternative. I personally have not tested it but it seems to do the same thing that OBS-NDI does: https://github.com/fzwoch/obs-teleport

2: Downgrade to OBS v27. The latest version before v28 was released is this one: https://github.com/obsproject/obs-studio/releases/tag/27.2.4 You also need to then use the current version of OBS-NDI, not the one I mentioned above: https://github.com/Palakis/obs-ndi/releases/tag/4.9.1

**Comment by Masihanurag** [comment] 2022-09-14 10:59
The NDI plugin started working in the OBS version 27.2


Thank you for supporting and resolved my problem.

**Comment by paulpv** [comment] 2022-09-16 01:37
@tt2468 please close

**Closed** 2022-09-16 01:40 UTC
