### ISSUE TITLE
Finds source, no image/audio.

### ISSUE THREAD

**Issue by Fiskarnxd** [Palakis/obs-ndi#262] opened 2018-12-28 02:26 UTC
Ayo lads!

The whole setup has worked for 20+ hours like a charm, without any problems, it has been pure pleasure actually. But a couple of days ago when I started both computers up as usual, it did not frickin work. Nothing has been changed, done, installed or anything on either of the computers. It has just aprubt stopped working.

The problem is that I can find the Gaming PC as a source on the Streaming PC, both in NDI monitor and OBS, but I dont get any image or audio.

The setup is connected through a 1GBps switch, and as I said, it has worked as a charm untill just now. I have tried a reinstall, tried with the firewall off on both computers, tinkering with all the  but I cant get any NDI fotage through whatsoever.

Here when testing both ways with NDI Monitor and tester.
**Gaming PC** : https://gyazo.com/36e72f85b775675150bfb7c549d7b899
**Streaming PC** : https://gyazo.com/a83701c1b15dc3a68c7b0aa6e8c1eb3f

**Streaming PC** : https://gyazo.com/422304acffae2fca657a37bef1d9af7c
**Gaming PC** : https://gyazo.com/819d8b3c392e8cfb76ccc77c22931ee2

As I said, its not the firewall as far as I can tell, since I have tried to run it 10 times with the firewall off on both computers. After tinkering for abit, with no luck to once again restore the flawless state that the entire setup was in, I tried to reinstall both obs and ndi, with no luck yet again.

Mediasharing is on.
**Gaming PC** : https://gyazo.com/c6cb73eaccb64acb402c3540371538e6
**Streaming PC** : https://gyazo.com/5d95c89941e567c953d35f45572d3e64

Whats the next approach in getting this getting back on track? What should I do?

Best and most festive regards, 
Isac

**Comment by Fiskarnxd** [comment] 2019-01-02 16:39
Anyone?

**Comment by Palakis** [comment] 2020-03-24 13:57
Duplicate of #62

**Closed by Palakis** 2020-03-24 13:57 UTC
Labels: black-screen
