### ISSUE TITLE
OBS crashes on selection of NDI source (Mac)

### ISSUE THREAD

**Issue by stevefal** [Palakis/obs-ndi#405] opened 2020-03-26 11:45 UTC
OBS Studio 24.0.6
MacOS Mojave 10.14.6
Mac Pro 2013 8-core 64GB dual D700
libndi.4.dylib from current http://new.tk/NDIRedistV4Apple - 4,132,576 bytes
obs-ndi 4.7.1

The OBS-NDI page on the OBS site says "This plugin requires the NDI 3.0 Runtime to be installed on your system. See installation instructions on the Downloads page for more details."

But the obs-ndi github download page says "This will install both the plugin and the NDI 4.0+ Runtime"

So I'm confused which version of the NDI runtime is currently required by obs-ndi.

In either case, here's my repro:

- Install Sienna signal generator (https://itunes.apple.com/us/app/ndi-signal-generator/id1080186452?ls=1&mt=12). Set it up with bars.
- OBS: add an NDI Source, Create New, select Signal Generator, OK
- OBSERVE: OBS quits unexpectedly.
[obscrash1.txt](https://github.com/Palakis/obs-ndi/files/4386900/obscrash1.txt)

The crash is not dependent on the Signal Generator. It's just a convenient source to select. I get a crash every time no matter which NDI source I select.

**Comment by Palakis** [comment] 2020-03-26 14:20
@stevefal With obs-ndi 4.7.1 you have to use NDI 4. I'm going to fix the resource on obsproject.com

**Comment by cmdtv** [comment] 2020-03-26 14:58
@Palakis How do you force NDI 4? Is there a way to get this working before you release an update?

**Comment by matteo897** [comment] 2020-03-26 16:52
Same problem here. 
When I add the NDI source, the program crashes.
How can I fix this? :-)

**Comment by corsa** [comment] 2020-03-26 18:48
Same problem here.
Downloaded and installed NDI runtime 4. Downloaded and installed ons-ndi 4.7.1.
Fired up Skype w/ NDI enabled, added source in OBS, and crashes.
macOS Catalina 10.15.4.

**Comment by mazerfaka** [comment] 2020-03-26 19:57
Same problem here, gonna have to do a stream tomorrow haha, crossing my fingers here !

**Comment by ajohnson880** [comment] 2020-03-26 20:26
Same issue. I have tried manually installing NDI runtime 4

**Comment by matteo897** [comment] 2020-03-26 20:36
> Same issue. I have tried manually installing NDI runtime 4

Does it work? How can I do that? I mean, installing NDI runtime 4 manually...

**Comment by ajohnson880** [comment] 2020-03-26 20:40
> > Same issue. I have tried manually installing NDI runtime 4
> 
> Does it work? How can I do that? I mean, installing NDI runtime 4 manually...

No it did not work

**Comment by matteo897** [comment] 2020-03-26 20:42
I just want to use the Plugin to stream live with Skype...

**Comment by eughenio** [comment] 2020-03-26 23:15
Hey @Palakis Can you guide how can we downgrade to version NDI 4?

**Comment by corsa** [comment] 2020-03-27 01:54
UPDATE: No idea why, but suddenly tonight it no longer crashes when selecting a source. I haven't changed anything since this afternoon when it was crashing, no reboots, etc. No clue why it suddenly started working?

**Comment by eughenio** [comment] 2020-03-27 02:09
Hey @corsa Which version of OBS and NDI are you using?

**Comment by corsa** [comment] 2020-03-27 02:10
OBS 24.0.6
NDI 4.5.0 (the new one released today)

**Comment by eughenio** [comment] 2020-03-27 02:13
> OBS 24.0.6
> NDI 4.5.0 (the new one released today)

Hey @corsa I've tried a lot of things nothing work.
Did you change some configuration on OBS or something?

**Comment by corsa** [comment] 2020-03-27 02:25
Not that I recall. At some point today, I did go in to /usr/local/lib and deleted libndi.3.dylib that was left lying around from NDI version 3.x, but I could have sworn I tested after removing that and it was still crashing. But I could be wrong, might be worth checking out on your side.

I did have a scene saved in OBS already had an NDI source set up (my Windows PC), and to test I fired up the Windows PC and saw the NDI stream fine on my mac. That was when I went to create a new source and was finally able to select a new NDI source (from Skype) without crashing.

But guess what? I just tested again, and now it is back to crashing every time I tried to add an NDI source!

**Comment by ajohnson880** [comment] 2020-03-27 02:28
So close!

**Comment by ruckusman** [comment] 2020-03-27 07:39
Got the same issue - MacOS 10.13.6 - start Skype with NDI enabled, add the NDI source - nothing actually appears in the dropdown list, but either typing something there OR leaving it blank and then clicking OK OBS crashes, consistently, every time

Let me know if uploading the crash report will be of any assistance

**Comment by mazerfaka** [comment] 2020-03-27 07:46
> OBS 24.0.6
> NDI 4.5.0 (the new one released today)

Where did you find the latest release?

**Comment by matteo897** [comment] 2020-03-27 08:15
> > OBS 24.0.6
> > NDI 4.5.0 (the new one released today)
> 
> Where did you find the latest release?

I’m looking for it too :)

**Comment by stevefal** [comment] 2020-03-27 08:24
> UPDATE: No idea why, but suddenly tonight it no longer crashes when selecting a source. I haven't changed anything since this afternoon when it was crashing, no reboots, etc. No clue why it suddenly started working?

I also got it to work exactly once right after a system reboot. But then it started crashing again immediately thereafter. I've since rebooted several time in order to reproduce the success case - with no success.

**Comment by ruckusman** [comment] 2020-03-27 08:25
It's here guys

https://ndi.tv/tools/

Ive tried it without any change to OBS crashing though

**Comment by stevefal** [comment] 2020-03-27 08:51
I think I'm seeing confusion of components and terms. Someone correct me if I'm wrong.

"NDI 4.5" as mentioned by @corsa refers to "NDI Tools for Mac", available at https://ndi.tv/tools/. It is a set of applets by Sienna for working with NDI streams. The disk image available there now does not contain Newtek's NDI dynamic link library (libndi.4.dylib), as far as I can see.

"NDI 4" as mentioned by @Palakis refers to Newtek's NDI dynamic link library that implements the foundation of all NDI operations on a system. If your mac has the file libndi.**4**.dylib at location usr/local/lib/, then you are running "NDI 4". If you only have libndi.**3**.dylib at that location, then you have NDI 3. NDI 4 is available from Newtek directly at http://new.tk/NDIRedistV4Apple.

Again, correct me if I'm misreading things.

**Comment by ruckusman** [comment] 2020-03-27 09:05
You are correct

You will also notice that the NDI Tools now has two individual packages available for download as DMG

I've tried removing that particular library and if you already have an NDI source selected in OBS, it will generate an error about the missing library - I did this just to check that it was definitely calling that library between the version 4 of NDI Tools and version 4.5 of NDI tools.

**Comment by stevefal** [comment] 2020-03-27 09:25
> You will also notice that the NDI Tools now has two individual packages

I actually can't see that because the download buttons on https://ndi.tv/tools/#download-tools don't work for me. I get an in-page message "Unable to display form. Sorry, a browser extension you are using is preventing the form from displaying. Please disable and try again." I've disabled everything and tried 3 browsers. No idea what's going on with that.

I got NDI Tools from Sienna via a link they sent me: http://sienna.tv/ndi/XX-REDACTED-XX/SiennaNDIToolsForMac.dmg. So, in fact, I can't confirm what you get from the download page at https://ndi.tv/tools/.

@Ruckusman what's in the two packages you're seeing from https://ndi.tv/tools/?

**Comment by ruckusman** [comment] 2020-03-27 09:38
I had the same problem with the page extension not working in Firefox so I switched to Safari which worked

I get two disk images
NewTekNDIHXDriverForMacOS.dmg
and 
NewTekNDIToolsForMacOS.dmg which has the same name as the previous 4.0 version - there is however a significant file size difference between the two

NewTekNDIToolsForMacOS.dmg for version 4.0 is 21.2MB whereas for version 4.5  it's 6.2MB

I've tried to locate the direct download links, however the script from the page deliberately obscures the direct link to the download.

Note I have seen no change with either version of the tools, both fail

**Comment by xseignard** [comment] 2020-03-27 10:35
Changed the `/usr/local/lib/libndi.4.dylib` with the following https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64 and I don't have crashes anymore.

**Comment by stevefal** [comment] 2020-03-27 10:36
I finally got the https://ndi.tv/tools/ downloads to work. The downloads are coming from:

- NDI Tools for Mac - http://new.tk/NDITOOLSAPPLE, redirected to http://514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/NewTekNDIToolsForMacOS.dmg

- NDI/HX Driver for Mac - http://new.tk/NDIHX-Driver-OSX, redirected to http://39a80d0ea5e9de8065d9-bfe57ec74076e9cb0c74346d8bd35c21.r97.cf1.rackcdn.com/NDIHX/OSX/NewTekNDIHXDriverForMacOS.dmg

Neither installs the core NDI driver libndi.4.dylib that I got at http://new.tk/NDIRedistV4Apple., which is coming from http://514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/libNDI_for_Mac.pkg

**Comment by matteo897** [comment] 2020-03-27 10:37
I installed all of the above... but OBS continues to crash everytime I add a NDI Source from SKYPE.

I think maybe it's a OBS problem itself... ? I don't know, unfortunately I'm not an expert here :-(

**Comment by mazerfaka** [comment] 2020-03-27 10:57
> libndi.4.dylib

I changed that but now it wont open saying that it's a malware that macOS doesn't recognize, the developer

**Comment by stevefal** [comment] 2020-03-27 11:02
@xseignard do you have information on the library at https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64? the file is about 600Kbytes smaller that the official library.

**Comment by matteo897** [comment] 2020-03-27 11:06
Where do I find the libndi.4.dylib ? So that I can change it?

**Comment by mazerfaka** [comment] 2020-03-27 11:09
Got It to work now ( I had to go into preferences while I was opening OBS to sign the file ) thank's stay safe stay home everyone !

**Comment by matteo897** [comment] 2020-03-27 11:10
> Got It to work now ( I had to go into preferences while I was opening OBS to sign the file ) thank's stay safe stay home everyone !

Can you please explain how you got it to work? :-) Like, step by step! :D

**Comment by mazerfaka** [comment] 2020-03-27 11:18
> > Got It to work now ( I had to go into preferences while I was opening OBS to sign the file ) thank's stay safe stay home everyone !
> 
> Can you please explain how you got it to work? :-) Like, step by step! :D

"I first installed the ndi sdk 4.5 (from here https://ndi.tv/sdk/) and OBS was crashing.

I then changed the /usr/local/lib/libndi.4.dylib with the following https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64 (supposed to be sdk 4.0) and I don't have crashes anymore." 

but I had to open preferences and allow obs to open with the new file! and then it worked!

**Comment by matteo897** [comment] 2020-03-27 11:21
WOW! That worked for me too!! :D

I didn't even had to allow OBS to open. I just changed that file, open OBS and... it works! 

Thank you! :-)

**Comment by ruckusman** [comment] 2020-03-27 11:28
> I first installed the ndi sdk 4.5 (from here https://ndi.tv/sdk/) and OBS was crashing.
> 
> I then changed the `/usr/local/lib/libndi.4.dylib` with the following https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64 (supposed to be sdk 4.0) and I don't have crashes anymore.

@xseignard - many many thanks for this - problem solved

**Comment by xseignard** [comment] 2020-03-27 11:29
@stevefal I've got no clues about the size difference. Are you sure you are comparing the same version of the static lib ? 
Please do remind that if you installed sdk 4.5 (like me), the one from https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64 is supposed to be sdk 4.0 hence the size difference. That's my guess.

**Comment by xseignard** [comment] 2020-03-27 11:35
So the issue seems to be related to people installing the sdk by themself instead of relying on this obs plugin to install the shared lib.

**Comment by stevefal** [comment] 2020-03-27 11:44
@xseignard I'm comparing the official lib to the one in the github repo.

Btw, the official NDI Mac SDK comes from http://new.tk/NDISDKAPPLE, which redirects to http://514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/InstallNDISDK_v4_Apple.pkg.

The libndi.4.dylib included in that download is the same as the one from http://new.tk/NDIRedistV4Apple. So even though the SDK is v4.5, the core NDI library within it is not distinguished from a version "4".

So maybe the library in the repo was the official one for SDK4.0, while the currently released one is in fact updated to support features of SDK4.5. If that assumption is correct, then maybe there is in fact an "NDI 4" and an "NDI 4.5", each of whose library file is indistinguishably named libndi.4.dylib.

Just theory. I'm not going to run the nariakiiwatani version until I know where it came from.

**Comment by eughenio** [comment] 2020-03-27 12:10
Hey guys, I did a test with the nariakiiwatani and works fine.
When you check the NDI Output settings it shows 2019 4.0.1.

**Comment by stevefal** [comment] 2020-03-27 12:21
Ah, great, and the current official one says Mar 25 2020 4.5.0.

Can anyone that used to have it working before the recent update use Time Machine to recover their old library? If so, you can compare it to the nariakiiwatani version to see if they're the same.

Meanwhile, I suppose whatever changed between NDI 4.0X and 4.5.0 produced a breakdown with OBS-NDI, which is probably why we're all here.

I don't have the old version because I just started working with OBS yesterday.

**Comment by eughenio** [comment] 2020-03-27 12:24
Is anyone using the version 4.5 and working?

**Comment by ruckusman** [comment] 2020-03-27 13:38
I just did a cmpdylib between the two - the symbols below aren't present in the nariakiiwatani library

I'd say something has to catch up for the new version of te library to work, which was from the package libNDI_for_Mac.pkg downloaded separately here
http://514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/libNDI_for_Mac.pkg

_NDIlib_framesync_capture_audio_v2
_NDIlib_framesync_free_audio_v2
_NDIlib_framesync_synchronize
_NDIlib_recv_capture_v3
_NDIlib_recv_free_audio_v3
_NDIlib_routing_get_no_connections
_NDIlib_routing_get_source_name
_NDIlib_send_get_connection_info
_NDIlib_send_get_no_connections_v2

**Comment by corsa** [comment] 2020-03-27 15:53
> So the issue seems to be related to people installing the sdk by themself instead of relying on this obs plugin to install the shared lib.

No, it appears that the new NDI 4.5 has a problem, and swapping to an older version (4.0.1) from nariakiiwatani seems to fix the problem. 

BTW, you can see which version of NDI you are running by going to the Tools > NDI Output Settings menu item in OBS.

**Comment by xseignard** [comment] 2020-03-27 20:01
Yeah you're right, I checked the install script of this plugin, and the bug should happen on fresh install of this plugin, even with no previous ndi sdk installs.

Not sure about the internals of this bug, but if a minor release (i.e not changing the leftmost number) breaks things, it is pretty alarming from ndi sdk developers...

**Comment by ruckusman** [comment] 2020-03-27 22:27
FWIW - I got the error from a clean install on a vanilla installation of 10.13.6.

Without installing the library separately NDI just wasn't available in the source menu to select.

The same error with OBS with both versions of the NDI tools, 4.0 & 4.5

**Comment by yurkomik** [comment] 2020-03-27 23:33
here is the pkg file with ndi runtime 4.0+ that works. Had it in downloads folder on another macbook
https://we.tl/t-DrewcFuseB

**Comment by mobleywho** [comment] 2020-03-28 01:05
> here is the pkg file with ndi runtime 4.0+ that works. Had it in downloads folder on another macbook
> https://we.tl/t-DrewcFuseB

Thank you! This pkg file was the only solution to work for me.

**Comment by kaydeelethal** [comment] 2020-03-29 06:36
I have a similar crushing problem

**Comment by mtaipe** [comment] 2020-03-29 09:56
Was not comfortable to use the pkg from WeTransfer and found a pkg with the same name on the CDN service that the 4.5 is shared, but still crashes:  http://www.514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/libNDI_for_Mac.pkg

**Comment by mveplus** [comment] 2020-03-29 17:45
Hi, 
I was playing today with it on my old MBP 2011 on macOS High Sierra 10.13.6 (17G12034).
OBS Studio ver: 24.0.6 ( had an older OBS before if it matters )
obs-ndi ver.4.7.1 & NDICam default settings, it was crashing  OBS Studio every time when I select source: Phone_name(NDICam)

I stumbled on this bug report, but after installing the [libNDI_for_Mac.pkg](http://new.tk/NDIRedistV4Apple) NDI 4.0+ Runtime - all is working fine. 

OBS NDI Output settings now reports: NDI SDK v.4.1.3 and I had no [NDI tools](https://ndi.tv/tools/) or [NDI SDK 4.5](https://ndi.tv/sdk/) packages installed previously.

Thanks guys great work!

**Comment by Unsoppable-YT** [comment] 2020-03-29 19:47
> here is the pkg file with ndi runtime 4.0+ that works. Had it in downloads folder on another macbook
> https://we.tl/t-DrewcFuseB

that's the same file that is on the NDI github page...

**Comment by GlomarSystems** [comment] 2020-03-29 20:01
I had the same crash issue when installing for the obsndi for the  first time 
Would crash on clicking OK after find an NDI source. 
I've tried so many combinations on a  Macbook Pro with OSX 10.14.6 
OBS Studio 24.0.6
OBS NDI 4.7.1  
Replaced file libndi.4.dylib at location usr/local/lib/ with version from https://we.tl/t-DrewcFuseB, now wouldn't crash but no NDI sources available. 
Then found McAfee firewall was ON  preventing connection to the source ! Turned it off and hey  Presto

**Comment by joechihe** [comment] 2020-03-30 22:44
Guys fixed mentioned here: https://obsproject.com/forum/threads/obs-ndi-crashes-upon-selecting-source-mac-high-sierra.117404/post-442968, worked for me.

**Comment by corsa** [comment] 2020-03-30 22:49
> Guys fixed mentioned here: https://obsproject.com/forum/threads/obs-ndi-crashes-upon-selecting-source-mac-high-sierra.117404/post-442968, worked for me.
> I read all the comments here, but seems older version of NDI still work on Mac OS Catalina

Yep, same fix @xseignard  mentioned earlier in this comment thread. :)

https://github.com/Palakis/obs-ndi/issues/405#issuecomment-604929253

**Comment by lgon44** [comment] 2020-04-02 03:42
> I first installed the ndi sdk 4.5 (from here https://ndi.tv/sdk/) and OBS was crashing.
> 
> I then changed the `/usr/local/lib/libndi.4.dylib` with the following https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64 (supposed to be sdk 4.0) and I don't have crashes anymore.

GUYS!! Found a solution after this step. When you try to open OBS, it'll say that "libndi.4.dylib" can't be opened because it is not identified. Do not open OBS after you have replaced "libndi.4.dylib". What you have to do first is DOUBLE-CLICK "libndi.4.dylib" (actually open it) and after that go to System Preferences and allow the computer to "open it anyway". After that you can open OBS and it will work. No more crashes.

**Comment by cookra** [comment] 2020-04-04 15:21
> > I first installed the ndi sdk 4.5 (from here https://ndi.tv/sdk/) and OBS was crashing.
> > I then changed the `/usr/local/lib/libndi.4.dylib` with the following https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64 (supposed to be sdk 4.0) and I don't have crashes anymore.
> 
> GUYS!! Found a solution after this step. When you try to open OBS, it'll say that "libndi.4.dylib" can't be opened because it is not identified. Do not open OBS after you have replaced "libndi.4.dylib". What you have to do first is DOUBLE-CLICK "libndi.4.dylib" (actually open it) and after that go to System Preferences and allow the computer to "open it anyway". After that you can open OBS and it will work. No more crashes.

I can confirm this worked of me.

**Comment by markklim** [comment] 2020-04-07 18:10
I am still getting crashes can someone break down how to change where I am needing to change the user file name or something to fix?  It works in streamlabs but not in OBS and I prefer OBS.  Here is the OBS quit unexpectedly report I got:

PS Im not savy with this stuff Im a realtor lol

[Untitled document.txt](https://github.com/Palakis/obs-ndi/files/4446304/Untitled.document.txt)

**Comment by worthyimage** [comment] 2020-04-07 20:07
> I am still getting crashes can someone break down how to change where I am needing to change the user file name or something to fix? It works in streamlabs but not in OBS and I prefer OBS. Here is the OBS quit unexpectedly report I got:
> 
> PS Im not savy with this stuff Im a realtor lol
> 
> [Untitled document.txt](https://github.com/Palakis/obs-ndi/files/4446304/Untitled.document.txt)

While in the Finder, use the top menu and choose **GO** > then select **Go to Folder** > then type in /usr/local/lib/ 
Then drag the libndi.4.dylib that you downloaded (https://github.com/nariakiiwatani/ofxNDI/tree/master/libs/NDI/lib/osx/x64) and drop it in the lib folder that you just opened to REPLACE the libndi.4.dylib that was already there.

It worked for me.

**Comment by Palakis** [comment] 2020-04-08 08:41
Fixed with #416

**Closed by Palakis** 2020-04-08 08:41 UTC
Labels: bug, macos

**Comment by stevefal** [comment] 2020-04-08 11:27
New build works for me on 4.5 now. Thanks @Palakis.

**Comment by andreapx** [comment] 2020-05-02 11:16
>  I get an in-page message "Unable to display form. Sorry, a browser extension you are using is preventing the form from displaying. Please disable and try again." I've disabled everything and tried 3 browsers. No idea what's going on with that.

I have this problem too. I've tried with a fresh install of FireFox/Chrome/Edge, with TOR but nothing I can't download the tools.

**Comment by lmsilvero** [comment] 2020-05-14 13:24
> > I get an in-page message "Unable to display form. Sorry, a browser extension you are using is preventing the form from displaying. Please disable and try again." I've disabled everything and tried 3 browsers. No idea what's going on with that.
> 
> I have this problem too. I've tried with a fresh install of FireFox/Chrome/Edge, with TOR but nothing I can't download the tools.

I have the same problem, but in my case I have blocked the some doubleclick.net URLs for example in my windows host file:
0.0.0.0	pubads.g.doubleclick.net 
0.0.0.0	static.doubleclick.net 
0.0.0.0	googleads.g.doubleclick.net 
0.0.0.0	pagead2.googlesyndication.com 
0.0.0.0 securepubads.g.doubleclick.net 
0.0.0.0	ad.doubleclick.net
So, the browser need to access to doubleclick URLs (I don't like but anyway!)
