### ISSUE TITLE
Stutter between two high-end PC's

### ISSUE THREAD

**Issue by Gigosh** [Palakis/obs-ndi#43] opened 2017-08-21 12:02 UTC
First and foremost, the development speed on this is pretty awesome. Thank you in advance for all the hard work put into this.

My issue is trying to use a two-pc streaming. Main PC is 5960x/1080ti gaming PC. Stream PC is Ryzen 1800x with RX460 GPU. Connectivity is Gigabit on the same switch (Both PC's using onboard Intel nics). Source OBS is 1440p canvas, downscaled to 1080p (bicubic) and sent to PC2 with 1080p canvas encoding for Twitch.

Quality is amazing, its just not smooth. Juddery at times, then its super smooth for a few seconds then it stutters and I can see the bandwidth vary (I'm assuming depending on scene complexity).

The bandwidth between the two PC's range from 30mbit idle to 160-180mbit during gameplay. I'm running OBS 20.0.1 with the latest NDI distribution from here. I can link you to the VOD if you want to see for yourself.

Do I need to perhaps have dedicated PCIE gigabit nics and crossover between them? Also is there a way to fix the bandwidth? What does the hardware acceleration actually do, use the source or destination GPU? Sorry for the ton of questions.

**Comment by gamespeaker** [comment] 2017-08-21 12:09
NDI needs 1GB connections.

**Comment by Gigosh** [comment] 2017-08-21 12:10
Yep each PC is 1gbit connected

**Comment by Eepi111** [comment] 2017-08-21 14:49
on my streaming pc i get like 1fps from the ndi source, through gigabit ethernet. But for some reason when using wifi on the stream pc it works fine.

**Comment by Gigosh** [comment] 2017-08-21 15:09
What brand is the stream PC's network card?

**Comment by Eepi111** [comment] 2017-08-21 17:20
Killer e2400

**Comment by Gigosh** [comment] 2017-08-22 06:56
Killer nics have always been problematic. Both PC's are onboard Intels for me.

**Comment by Gigosh** [comment] 2017-08-23 14:55
Ok so if I game capture from source OBS its woeful performance, lots of stutter and chugging sending 1080p downscaled from 1440p over the network.

The moment I use Display Capture its day and night difference better. Not sure if its a frame buffer + ndi encode performance issue but the moment its display capture its almost perfect.

**Comment by Roxasnovaliches** [comment] 2017-08-25 23:24
I can also reproduce this bug with my 2 pc setup.

**Comment by Farmagud** [comment] 2017-08-30 07:36
Same issue with my setup. Gaming PC has a Ryzen 1700x and a GTX 1080 while my streaming PC has a i7 2600 and a GT 1030. Performance is much better using Display capture rather than game capture, but it’s still not perfect. 

The stream will start out smooth but quickly deteriorate into a stuttering mess in less than 10 minutes.

Both PCs are hooked up to a Gigabit LAN switch with CAT6 cables.

Interestingly, XSplit seems to have the same issue.

**Comment by Farmagud** [comment] 2017-08-31 02:23
Just tried again, XSplit seems to work fine when sending a game capture over to OBS on the encoding PC. Might be an issue with OBS's capture method.

**Comment by Palakis** [comment] 2017-08-31 17:43
> Do I need to perhaps have dedicated PCIE gigabit nics and crossover between them? Also is there a way to fix the bandwidth?

Dedicated GigE NICs are necessary only with more than two NDI streams in one direction. Using a crossover cable between the two computers isn't of much help here, except if you want to reuse the switch for something else.
Speaking of switches, make sure the Ethernet switch linking the two computers is a Gigabit Ethernet switch, and that the two computers show a Gigabit link (seen either in Windows or on the switch's status LEDs)

> What does the hardware acceleration actually do, use the source or destination GPU? 

It applies to the NDI receiver in OBS, so the destination GPU is used.

@Gigosh 
> The moment I use Display Capture its day and night difference better. Not sure if its a frame buffer + ndi encode performance issue but the moment its display capture its almost perfect.

Maybe an issue with video or audio frame timestamps. Does the OBS logs show messages like "added x ms of audio buffering"?

@Roxasnovaliches 
> I can also reproduce this bug with my 2 pc setup

Can you also reproduce the workaround discovered by @Gigosh?

**Comment by Gigosh** [comment] 2017-09-01 03:38
@Palakis Everything is gigabit, nic to switch. What I have noticed is if I drop my graphics settings the stream becomes very smooth. I think its got to do with the preview rendering on gaming PC needing GPU. I have a 1080ti but the moment I cap game framerate or drop quality to give it some breathing room it becomes smooth. Usually GPU is 99% usage trying to achieve the highest framerate. 

I have confirmed this by running 1440p 60fps video on main pc with display capture and the stream PC is perfect. Its OBS rendering with not enough GPU I'm assuming.

**Comment by Palakis** [comment] 2017-09-28 07:16
I released 4.1.3 minutes ago. It fixes some timing/sync issues, so you may be interested in trying this latest release.

**Comment by Palakis** [comment] 2017-10-02 13:05
I repeat to everybody who had this issue with obs-ndi: please try the latest release, as it fixes an important timecode problem.

**Comment by Daner01** [comment] 2017-10-03 16:14
I'm also having this issue but using the workaround @Gigosh didnt fix the issue for me. I have found that if OBS is no longer in focus it will degrade the performance down to 30-40 FPS but the moment OBS is back in focus it will jump back to smooth 60 FPS on the source PC. Source PC is a I7 7700k Asus Strix 1080TI also check that it does have a 1 GB to my stream PC that is I7 3770k Nvidia 960.

**Comment by BadsStar** [comment] 2017-10-11 13:05
> I repeat to everybody who had this issue with obs-ndi: please try the latest release, as it fixes an important timecode problem.

I've been using 4.1.3 since release and it seems to have fixed my issue!

[4.1.3 NDI OBS Plugin - 60 FPS Footage](https://go.twitch.tv/videos/181338656)

**Comment by MASSIVELIVEFUN** [comment] 2017-10-27 00:36
I am sending from my desktop to my laptop and it seems to handle 1080p 30 extremely well. However, I go to 1080p 60 and according to my netgraph on my desktop's and laptop's task manager both computers are having a hernia, respectively. The smooth line that i would see on the netgraph with 1080p 30 becomes a inconsistent jagged mountain range with 1080p 60. Contributing to the choppy footage on my laptop and my test streams. It seems from other posts that cases involving monitor native source resolutions have problems with choppy footage.

My network is all gbps. My equipment consists of Cat 6 cables, 10/100/1000 switch boxes, fast nvidia cards, i7's, the works. I dont understand how a simple change can mess everything up.

I'll send debug information i just dont know what to send. I just need help with this issue.

**Comment by wazerstar** [comment] 2017-10-27 06:30
There's some serious issues still, example running a game capture on this map in CSGO and when the "grey" color starts from smokes, it stutters like mad almost like the recording stops for a few seconds and then gets back into recording.

https://steamcommunity.com/sharedfiles/filedetails/?id=500334237

Using display capture vs game capture is night and day for me too

**Comment by koeniig2** [comment] 2017-11-23 22:58
any solutions?? i got the same problem, it stutter every few seconds.

**Comment by Palakis** [comment] 2017-11-27 16:28
Can't remember where, but I remember talking with somebody about disabling TCP congestion control (NDI uses TCP) on the system.

**Comment by Helgaiden** [comment] 2017-11-27 17:28
@palakis
I remember reading that one. 
Command prompt with admin privleges then type 
Netsh int tcp reset

That or it's netsh int in reset. Or both. I don't remember. Easy and quick though.

**Comment by Denkimon** [comment] 2017-12-01 22:17
Hey everyone, did you guys manage to get the stuttering fixed? I've been trying stuff myself but have not managed to get it to be smooth 60 FPS.

**Comment by Helgaiden** [comment] 2017-12-01 22:21
i''ve been using NDI thru OBS for months. Never had stuttering issues but i also ensured that my connections on both PCs (and the switch) are gigabit 10/100/1000. Most of the time people have had issues, its because one or both computers weren't on gigabit, or they thought it would be fine over WiFi. I would check that, do the command prompt commands in my previous message above this one, and go from there.

**Comment by Denkimon** [comment] 2017-12-01 22:26
That's interesting, when i run the prompt command you posted previously i get the text "Reset of all TCP parameters OK! Ok." that's it. 

Maybe i'm not on a gigabit connection then. When i open the Ethernet status it says speed "100.0 Mbps" would i be required to have "1 Gbps" there?

**Comment by Helgaiden** [comment] 2017-12-01 22:32
Your command operation worked. However yes, where it says "100.0 Mbps" it should say "1 Gbps." That is probably the source of your issue. Check your computer's ethernet port to see if its fast ethernet (10/100) or gigabit, and also check the 2nd computer for same, and check that your router/switch's ports you're connected to are also Gigabit capable. You can lookup the model of the router/switch to find that info.

**Comment by Denkimon** [comment] 2017-12-01 22:37
Oh alright, i realize now that my router does not have gigabit speeds, both my computers do have gigabit speeds available on their motherboards! also i found your stream and checked your VOD and it looks great. silky smooth 60 fps, i'm happy to see that it's just me that's doing something wrong since i dont have the money to spend on a expensive capture card at the moment! Thanks for the help Helgaiden!

**Comment by Helgaiden** [comment] 2017-12-01 22:52
Happy to help. Glad you found the stream and you liked it.

**Comment by Palakis** [comment] 2017-12-11 09:52
> Quality is amazing, its just not smooth. Juddery at times, then its super smooth for a few seconds then it stutters and I can see the bandwidth vary (I'm assuming depending on scene complexity).

I had a similar issue three weeks ago during a live show, sending 2x NDI streams from vMix Desktop Capture to one OBS. Didn't much more debugging then, but I guess it was a bandwidth issue.

> Do I need to perhaps have dedicated PCIE gigabit nics and crossover between them?

No, no need for dedicated NICs or crossover cable. Just make sure the network (NICs + switches + cables) is fully Gigabit Ethernet-capable.
Also make sure the Gigabit switch detects connected NICs and cables as Gigabit Ethernet, and doesn't downgrade any link to 100 Mbit/s in case of a defective cable or NIC. This can be easily checked with the blinking lights color of each port (generally orange for 100 Mbit/s and green for 1000 Mbit/s, but check your switch's manual for correct colors).

> Also is there a way to fix the bandwidth?

Have a look at this: https://github.com/Palakis/obs-ndi/issues/59
Looks like the installer of the NDI runtime changes a setting that reduces available bandwidth on Windows.

> What does the hardware acceleration actually do, use the source or destination GPU?

It's hardware-accelerated decoding, so it uses the destination GPU.

> Sorry for the ton of questions.

I'm here to help! 😄

**Comment by sorenhoyer** [comment] 2018-01-27 23:08
@Palakis it's still not clear to me, whether chosing "allow hardware acceleration" will impact image quality?

**Comment by PizzaPeter1998** [comment] 2018-02-11 05:34
@Helgaiden I had the same issue not long ago however I sorted it out by distributing my resources effectively throughout both PC's which then allowed me to stream at 900p @60FPS as the issue occurred due to **lagged frames** which then reflect upon your streaming.

One thing you have to take into consideration is that OBS uses your GPU no matter what as this is how the software is built in order to capture and render the scenes which then takes the information of your output resolution as well as your FPS using your GPU to send it to the encoder or over NDI.

The common solutions for this is to lower your games GPU usage by using FPS limiters, lowering GPU  based details or enabling V-Sync.

Unfortunately lagged frames and other issues around it are not caused 100% by GPU usage but the issues can also be inherent issues for example Windows 10, Nvidia or AMD that unfortunately does not split the usage and resources effectively  which means that in some cases it will provide priority of the game over OBS which will take resources away from it in which it needs as OBS is quite demanding, its pretty much hit and miss as one user with a 1080ti will lag frames and another user with a 1080ti might not it doesn't really make sense.

I hope this helps!

**Comment by WreckedMech** [comment] 2018-12-07 06:10
So I made a bit of a discovery regarding those lost frames.

In a two system setup I was getting major frame drops on the incoming NDI connection. The OBS monitor on the giving side appeared smooth, but the receiving OBS was far from it. The odd solution was to Minimize a browser window i had set to monitor my Twitch broadcast. Not Close, just Minimize, although i bet closing works too. 

My advice if your having the OBS-NDI frame loss issue is to go through your windows and minimize them until you locate the one causing the stutter by being active.

**Closed** 2019-03-08 20:48 UTC
Labels: unstable-framerate

**Comment by TheOnlyTwiTchR6** [comment] 2019-03-14 13:12
It took me 3 second to realize my ndi stream stuttering was due to high gpu usage, every time I hit 100% usage (like it should be for high refresh rate gaming) my stream PC stutters like crazy. The second I add vsync with a low frame cap, or lower detail until my cpu because message the bottleneck then it'll be a smooth 60fps stream.

Other than enabling a frame cap, is there a way to limit gpu usage to around 90% while using ndi, or set the PC to prioritize ndi usage over the game so the stuttering issue can get fixed?

I'm using both the newest version of obs, and ndi

**Comment by Helgaiden** [comment] 2019-03-14 19:29
@TheOnlyTwiTchR6 Depending on your game, especially a game like Apex Legends, Blacks Ops 4 Blackout, and i think Forza Horizon 4 amongst others, the way the game works is that it demands everything from the GPU leaving nothing left for OBS to render itself to run at 60fps. This has nothing to do with NDI and everything to do with the way Windows 10 interacts with OBS Studio. There are a few solutions to maintain stream smoothness with games coded this way. I know because i've encountered the same issues with my 144hz screen the above stated games.

1. Lower your game settings enough that OBS FPS output smooths out. If just lowering your game settings doesn't fix this, then you have to start lowering your refresh rate and turn V-Sync on in the games you're playing. This will ensure enough GPU resources are leftover for OBS to operate properly.

2. Use a capture card.

Here is more information on your issue.

https://www.youtube.com/watch?v=OyjeJVwKoq0
