### ISSUE TITLE
OBS capture on single machine, NDI detected but no preview

### ISSUE THREAD

**Issue by stinkhorse** [Palakis/obs-ndi#176] opened 2018-06-18 01:22 UTC
So my issue is OBS refuses to display a preview from my NDI source being streamed from Adobe Character Creator. The machine is a Microsoft Surface tablet.

I've checked the capture issue with NDI Tools and it displays my feed fine in that. I can even reference that window in OBS as a crude work around but I would rather stream it correctly so I can output with an alpha'd background rather than a black field. I've tried the various solutions like turning off my firewall or providing exceptions. I've even made sure to switch on window's own internal media streaming toggle under networking.

![image](https://user-images.githubusercontent.com/10891746/41514370-3deb1690-725b-11e8-8c0c-0e60ad86cc20.png)

I don't know a lot about trouble shooting beyond looking up other people's solutions so I'm at a loss here.

**Comment by stinkhorse** [comment] 2018-06-18 14:50
Well I've butchered together a suitable solution to my problem by cropping and chroma keying my character from Character Animator itself. This will work for me but the underlying problem remains extant.

**Comment by Helgaiden** [comment] 2018-06-18 14:59
i dont think the preview window ever shows anything, that hasn't been my experience with OBS NDI. You select your source, preview window remains black, then you press OK to accept it, and then it goes into the main OBS window and after a second or two, it pops in. Try putting both PCs in the same Homegroup, and also power cycle your router.

**Comment by Palakis** [comment] 2020-03-24 13:35
Closing this as it's a duplicate of #62

**Closed by Palakis** 2020-03-24 13:35 UTC
Labels: black-screen, no-signal, video
