### ISSUE TITLE
I am unable to get NDI runtime to be found by OBS Studio.

### ISSUE THREAD

**Issue by DrakeekarD** [Palakis/obs-ndi#346] opened 2019-09-17 00:58 UTC
I have tried this multiple times, I have done a fresh install of NDI runtime, restart, install OBS, restart, install the OBS-NDI plugin, restart, and every time I get NDI Runtime not found. Here is my log file.

[2019-09-16 18-49-48.txt](https://github.com/Palakis/obs-ndi/files/3618751/2019-09-16.18-49-48.txt)

**Comment by narcogen** [comment] 2019-09-17 01:12
Same issue here.

The shortened URL now goes to the NDI 4 runtime, and in the logfile, the module finds this... and then doesn't find it?

21:10:31.725: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v3/Processing.NDI.Lib.x64.dll'
21:10:33.178: [obs-ndi] Can't find the NDI library

**Comment by narcogen** [comment] 2019-09-17 01:15
Works if you replace the 4.0 runtime with the older 3.8 runtime.

**Comment by RockNRollGeek** [comment] 2019-09-17 01:20
> Works if you replace the 4.0 runtime with the older 3.8 runtime.

Dont do that. Then you're basically losing the benefits of NDI 4.0. Either remove all NDI 4 and it's tools off your machine, and install the 3.8 runtime so you're using 3.8 across the board, -or- sit tight, there appears to be an obs-ndi update dropping very soon, so that you can install NDI 4 end to end and get the benefits.

**Comment by DrakeekarD** [comment] 2019-09-17 02:30
I will wait for the installer then, boy did I pick a bad time to try and switch my streaming setup lol.

**Comment by narcogen** [comment] 2019-09-17 03:37
> > Works if you replace the 4.0 runtime with the older 3.8 runtime.
> 
> Dont do that. Then you're basically losing the benefits of NDI 4.0. Either remove all NDI 4 and it's tools off your machine, and install the 3.8 runtime so you're using 3.8 across the board, -or- sit tight, there appears to be an obs-ndi update dropping very soon, so that you can install NDI 4 end to end and get the benefits.
> 
> Edit: It appears the source code is already updated and in the releases section, so you could take that and run with it, otherwise wait for the installer's to be built.

Not sure I follow you. I said I removed NDI4 and replaced it with the old version, then you said don't do that, but to remove NDI4 and replace that with the older version.. which is what I did.

The NDI4 installer has no benefits for me if the OBS-NDI plugin doesn't function, because that's what I installed it for. I'll keep my current working configuration until there's notice here that the plugin works with the new runtime. "Sitting tight" and waiting for it with NDI 4 installed and a non-working copy of OBS isn't an option.

**Comment by liquidvisual** [comment] 2019-09-17 03:48
I thought this issue was Mac specific (which is what I have) but it seems to be happening everywhere. 

@RockNRollGeek Where can I find the 3.8 runtime? Is there a proper way to uninstall 4.0 before installing 3.8?

**Comment by RockNRollGeek** [comment] 2019-09-17 04:00
> > > Works if you replace the 4.0 runtime with the older 3.8 runtime.
> > 
> > 
> > Dont do that. Then you're basically losing the benefits of NDI 4.0. Either remove all NDI 4 and it's tools off your machine, and install the 3.8 runtime so you're using 3.8 across the board, -or- sit tight, there appears to be an obs-ndi update dropping very soon, so that you can install NDI 4 end to end and get the benefits.
> > Edit: It appears the source code is already updated and in the releases section, so you could take that and run with it, otherwise wait for the installer's to be built.
> 
> Not sure I follow you. I said I removed NDI4 and replaced it with the old version, then you said don't do that, but to remove NDI4 and replace that with the older version.. which is what I did.
> 
> The NDI4 installer has no benefits for me if the OBS-NDI plugin doesn't function, because that's what I installed it for. I'll keep my current working configuration until there's notice here that the plugin works with the new runtime. "Sitting tight" and waiting for it with NDI 4 installed and a non-working copy of OBS isn't an option.

[1]. Chill.
[2.] Possibly misread, assumed you have the ndi 4.0 tools and had then installed obs-ndi, which was having the issue grabbing the 4.0 runtime, was saying to remove the 4.0 tools and the runtime, not just the runtime. 
[3.] since you absolutely can't wait a few hours and have to use ndi in obs right this second, if you've got the 4.0 ndi tools installed, just use scan converter on your source pc, full screen studio monitor on your obs pc, and in obs do a window capture of studio monitor instead of direct ndi.

**Comment by RockNRollGeek** [comment] 2019-09-17 04:05
> I thought this issue was Mac specific (which is what I have) but it seems to be happening everywhere.
> 
> @RockNRollGeek Where can I find the 3.8 runtime? Is there a proper way to uninstall 4.0 before installing 3.8?

last I checked, direct links to 3.8 now auto redirect to 4. not sure where a copy of 3.8 would be, you might have to google around. That said, as I mentioned earlier, The project owner has already been doing updates to address the issue, source code for the fix is available, so it's likely just a matter of waiting for the new binaries. You could also try out the mac release from the releases page that was 2 versions ago and see if that has everything bundled in that you need?

**Comment by Palakis** [comment] 2019-09-17 08:28
@RockNRollGeek Yeah, NewTek somehow fucked up and redirects the V3 links to V4.

**Comment by Palakis** [comment] 2019-09-17 08:28
Duplicate of #343

**Comment by Palakis** [comment] 2019-09-17 08:30
@DrakeekarD the installers are available! https://github.com/Palakis/obs-ndi/releases/tag/4.7.0

**Closed** 2019-09-17 12:12 UTC
Labels: duplicate

**Comment by DrakeekarD** [comment] 2019-09-17 16:46
Thanks.
