### ISSUE TITLE
[Linux] OBS Crashes when Creating Source & Dedicated Output not Working

### ISSUE THREAD

**Issue by IamDH4** [Palakis/obs-ndi#10] opened 2016-12-15 08:07 UTC
Using what I assume is the latest version of the SDK, I was only given one option to download directly from Newtek. Upon first launch I was met with this error:
```
error: os_dlopen(/usr//lib/obs-plugins/obs-ndi.so->/usr//lib/obs-plugins/obs-ndi.so): libndi.so.1: cannot open shared object file: No such file or directory

warning: Module '/usr//lib/obs-plugins/obs-ndi.so' not found
```
Creating a symlink at `/usr/lib/libndi.so.1` got me into OBS. Not sure why I had to do that?

NDI Output works (but with significant lag).

Creating a new NDI source immediately crashes OBS with:
```
fish: “obs” terminated by signal SIGSEGV (Address boundary error)
```

 The Dedicated Output Filter does appear on the network, but there is no feed. OBS does throw some errors:
```
error: Failed to fetch parent window geometry!
error: gl_platform_init_swapchain  failed
error: obs_display_init: Failed to create swap chain
info: User added filter 'Dedicated NDI output' (ndi_filter) to source 'Screen Capture (XSHM)'
```

Here is the entire OBS output before I start making changes:
```
dh4@dh4-desktop-1 /u/lib> obs
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Default.qss
Attempted path: /usr/share/obs/obs-studio/themes/Default.qss
Attempted path: share/obs/obs-studio/license/gplv2.txt
Attempted path: /usr/share/obs/obs-studio/license/gplv2.txt
info: Processor: 6 logical cores
info: Processor: AMD FX(tm)-6300 Six-Core Processor
info: Physical Memory: 8001MB Total
info: Kernel Version: Linux 4.8.13-1-ARCH
info: Distribution: "Antergos Linux" Unknown
info: Portable mode: false
QObject::connect: invalid null parameter
info: OBS 0.16.6-1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: OpenGL version: 3.2.0 NVIDIA 375.20

info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
info: ---------------------------------
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
info: No blackmagic support
info: NVENC supported
info: [obs-ndi] hello ! (version 0.3.2)
info: ---------------------------------
info:   Loaded Modules:
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info: ==== Startup complete ===============================================
error: Service '' not found
info: Switched to Preview/Program mode
info: ------------------------------------------------
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 9.0'
error: pulse-input: An error occurred while getting the source info!
info: pulse-input: Server name: 'pulseaudio 9.0'
error: pulse-input: An error occurred while getting the source info!
info: xshm-input: Geometry 1920x1080 @ 0,0
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Screen Capture (XSHM)' (xshm_input)
info: ------------------------------------------------
info: Update check: last known remote version is 0.4.0
```

**Comment by Palakis** [comment] 2016-12-15 09:02
The `gl_platform_init_swapchain  failed` error of the Dedicated Output seems to be caused by the lack of a window handle in the swap chain parameters (see this #ifdef block : https://github.com/Palakis/obs-ndi/blob/master/obs-ndi-filter.cpp#L145).
Regarding the library load error, you might need to run `ldconfig` after install.

**Comment by Palakis** [comment] 2017-03-01 16:55
Regarding Linux support, I implemented dynamic library loading of the NDI library and hasn't tested it on Linux yet. So the latest master is not compatible with Linux atm.

**Comment by Palakis** [comment] 2017-04-22 18:54
@IamDH4 Fixed in the latest version of code. Here's an automated build for you or anyone to test : http://obs-ndi-linux-builds.s3-eu-central-1.amazonaws.com/obs-ndi_1-0b1c363-master-git-1_amd64.deb (link valid for some days before deletion)

**Closed by Palakis** 2017-04-22 18:54 UTC
