### ISSUE TITLE
OBS Ndi Blank Screen over 10gb Network

### ISSUE THREAD

**Issue by yihwoei27** [Palakis/obs-ndi#212] opened 2018-09-11 00:57 UTC
On my OBS Stream PC, I get a blank screen when the target source is the gaming PC. Ive read some post about fixing this. All has not fixed my issue.

My gaming PC is on a 10gb SFP+ network card. And my Streaming PC is on 1gb Cat6. So Ive tried all the fixes and then I thought to myself what if I used a 1gb Cat6 instead of running my 10gb. And lone and behold, I can see the gaming PC source on the streaming PC.

Now my question is why is this happening and how can it be fixed because Id like to stay on my 10gb for the transfer speed to my NAS.

NAS and Gaming PC is on 10gb SFP+ Fiber to a switch that has SFP+ ports and 24 POE RJ45 ports. So that means everything is on the same switch.

**Comment by yihwoei27** [comment] 2018-09-11 01:26
Ok so set to low quality in the NDI capture makes the video stream, but its super low quality.

**Comment by Palakis** [comment] 2020-03-24 13:40
Duplicate of #62

**Closed by Palakis** 2020-03-24 13:40 UTC
Labels: black-screen, network-interference, no-signal
