### ISSUE TITLE
Lag / Stutter

### ISSUE THREAD

**Issue by koeniig2** [Palakis/obs-ndi#66] opened 2017-11-24 10:49 UTC
hy,

i got 1 gaming pc (i7-4790k, R9-290) 
and 1 streaming setup (AMD FX 8350)

So when i stream, the quality is good but after every 5 seconds it stutter and lag. I have tried all settings in OBS but i think it is a network problem, cause other people got the same issue with other streaming-rigs.

how you guys handle this?

**Comment by Palakis** [comment] 2017-11-27 08:57
Duplicate of #43. Please contribute there.

**Comment by koeniig2** [comment] 2017-11-28 15:51
still trash

**Closed** 2017-11-28 16:31 UTC
Labels: duplicate

**Comment by Palakis** [comment] 2017-11-28 16:56
Please mind your language, and take into consideration the work done by contributors and myself on this open source project.
This issue has been known for a while but still lacks a definitive explanation and fix. I've encountered it too, and I'm still not sure if it's an issue within obs-ndi's code or in the NDI runtime (which I don't have much control on).
