### ISSUE TITLE
Linux to Linux NDI no Output or Source video or audio

### ISSUE THREAD

**Issue by 0lzi** [Palakis/obs-ndi#362] opened 2019-10-18 07:15 UTC
Gaming/Streaming machine : Linux mint 19.2 , latest OBS from PPA.

Laptop : Ubuntu 18.04 , latest OBS from PPA

Set up laptop with NDI main output, and preview and add screen capture in scene, add filter to screen capture for dedicated NDI output.

On PC add NDI source, all three sources are visible, OBS , OBS ( Preview ) , NDI Dedicated output. Resize the output, and nothing is displayed, and no sound.

Do the opposite and go from gaming pc to laptop and same result.

**Comment by secstu** [comment] 2020-01-04 19:46
Hey did you figure out what was the issue?

**Comment by Palakis** [comment] 2020-03-24 14:21
Duplicate of #62

**Closed by Palakis** 2020-03-24 14:21 UTC
Labels: black-screen, duplicate
