### ISSUE TITLE
Old issue, but not finding a solution 

### ISSUE THREAD

**Issue by rma74** [Palakis/obs-ndi#432] opened 2020-04-08 16:29 UTC
Using osx newest obs version
downloaded and installed successfully  NDI 4.0+ Runtime files provided 
Getting the failed installation pop up for obs-ndi-4.7.1-macOS.pkg
I've downloaded Newtek files in response from other solutions
Mac is running High Sierra
Any advice?

**Comment by Palakis** [comment] 2020-04-09 01:24
@rma74 Grab the .pkg installer under `macos_build` here: https://dev.azure.com/Palakis/obs-ndi/_build/results?buildId=1089&view=artifacts&type=publishedArtifacts
And then install the NDI Runtime manually.

Starting with 4.8.0, to prevent that kind of error, the installer will not try to install the NDI runtime automatically.

**Comment by Palakis** [comment] 2020-04-09 01:26
Duplicate of #412

**Closed by Palakis** 2020-04-09 01:26 UTC
