### ISSUE TITLE
NDI Plugin causing OBS to crash [Ubuntu]

### ISSUE THREAD

**Issue by airwasp** [Palakis/obs-ndi#179] opened 2018-06-26 01:06 UTC
Good evening,

I'm trying to get a dual-pc streaming setup going, so this NDI concept sounds fantastic.
So first off - major thanks for putting in the work and making this plugin possible.

I'm running Ubuntu 16.04, I've got the latest version of OBS, and the latest versions of both libndi and obs-ndi.

When I installed libndi/obs-ndi, everything seemed to be operational.
I was able to see 'NDI Output settings' under 'Tools'.
I left the Output name default (OBS), and checked the box to 'Enable NDI Output'.

After pressing 'OK', OBS Crashed, and it can't seem to get OBS to open as long as I have obs-ndi installed.

If I do sudo apt-get remove obs-ndi, OBS comes up fine, and I can record and stream as if nothing happened; but I want this NDI plugin to start working.

Anything that I can provide you to remedy this, I'm willing to.  Below are the log files from terminal.

Thanks in advance!

> patrick@patrick-Ub16:~$ obs
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
Attempted path: share/obs/obs-studio/license/gplv2.txt
Attempted path: /usr/share/obs/obs-studio/license/gplv2.txt
info: CPU Name: AMD A4-3300M APU with Radeon(tm) HD Graphics
info: CPU Speed: 1348.113MHz
info: Physical Cores: 2, Logical Cores: 2
info: Physical Memory: 5435MB Total, 3554MB Free
info: Kernel Version: Linux 4.13.0-45-generic
info: Distribution: "Ubuntu" "16.04"
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 21.1.0 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD SUMO (DRM 2.50.0 / 4.13.0-45-generic, LLVM 5.0.0)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 17.2.8, shading language 3.30
info: ---------------------------------
info: video settings reset:
	base resolution:   1600x900
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
info: No blackmagic support
info: [obs-ndi] hello ! (version 4.1.3)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.3'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully
info: [obs-ndi] starting main NDI output with name 'OBS'
info: [obs-ndi] asynchronous video sending disabled
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info: ---------------------------------
info: ==== Startup complete ===============================================
error: Service '' not found
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 8.0'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 8.0'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_14.2.analog-stereo'
info: xshm-input: Geometry 1600x900 @ 0,0
Illegal instruction (core dumped)

**Comment by Palakis** [comment] 2018-07-06 12:35
@airwasp Can you try using the latest development build, please?
Plugin: http://obs-ndi-linux-builds.s3-eu-central-1.amazonaws.com/obs-ndi_1-ebd46a4-master-git-1_amd64.deb
NDI 3.5 runtime: http://obs-ndi-linux-builds.s3-eu-central-1.amazonaws.com/libndi3_3.5.1-1_amd64.deb

**Comment by airwasp** [comment] 2018-07-07 02:04
Hello @Palakis 

I put a fresh Ubuntu 16.04 on my system so as to make sure there are no previous versions on, then did a fresh install with those two items (NDI OBS Plugin, and NDI 3.5 Runtime).

Still crashes when NDI Plugin is active.  Below is the log

> patrick@Patrick-Ubuntu:~$ obs
> Attempted path: share/obs/obs-studio/locale/en-US.ini
> Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
> Attempted path: share/obs/obs-studio/locale.ini
> Attempted path: /usr/share/obs/obs-studio/locale.ini
> Attempted path: share/obs/obs-studio/themes/Dark.qss
> Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
> Attempted path: share/obs/obs-studio/license/gplv2.txt
> Attempted path: /usr/share/obs/obs-studio/license/gplv2.txt
> info: CPU Name: AMD A4-3300M APU with Radeon(tm) HD Graphics
> info: CPU Speed: 1413.254MHz
> info: Physical Cores: 2, Logical Cores: 2
> info: Physical Memory: 5435MB Total, 3584MB Free
> info: Kernel Version: Linux 4.13.0-45-generic
> info: Distribution: "Ubuntu" "16.04"
> info: Portable mode: false
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
> QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
> info: OBS 21.1.0 (linux)
> info: ---------------------------------
> info: ---------------------------------
> info: audio settings reset:
> 	samples per sec: 44100
> 	speakers:        2
> info: ---------------------------------
> info: Initializing OpenGL...
> info: Loading up OpenGL on adapter X.Org AMD SUMO (DRM 2.50.0 / 4.13.0-45-generic, LLVM 6.0.0)
> info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 18.0.5, shading language 3.30
> info: ---------------------------------
> info: video settings reset:
> 	base resolution:   1600x900
> 	output resolution: 1280x720
> 	downscale filter:  Bicubic
> 	fps:               30/1
> 	format:            NV12
> 	YUV mode:          601/Partial
> info: Audio monitoring device:
> 	name: Default
> 	id: default
> info: ---------------------------------
> libDeckLinkAPI.so: cannot open shared object file: No such file or directory
> info: No blackmagic support
> info: [obs-ndi] hello ! (version 4.4.0)
> info: [obs-ndi] Trying ''
> info: [obs-ndi] Trying '/usr/lib'
> info: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.3'
> info: [obs-ndi] NDI runtime loaded successfully
> info: [obs-ndi] NDI library initialized successfully
> error: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: cannot open shared object file: No such file or directory
> 
> info: Couldn't find VLC installation, VLC video source disabled
> info: ---------------------------------
> info:   Loaded Modules:
> info:     vlc-video.so
> info:     text-freetype2.so
> info:     rtmp-services.so
> info:     obs-x264.so
> info:     obs-transitions.so
> info:     obs-outputs.so
> info:     obs-ndi.so
> info:     obs-libfdk.so
> info:     obs-filters.so
> info:     obs-ffmpeg.so
> info:     linux-v4l2.so
> info:     linux-pulseaudio.so
> info:     linux-jack.so
> info:     linux-decklink.so
> info:     linux-capture.so
> info:     linux-alsa.so
> info:     image-source.so
> info:     frontend-tools.so
> info: ---------------------------------
> info: ==== Startup complete ===============================================
> error: Service '' not found
> info: No scene file found, creating default scene
> info: All scene data cleared
> info: ------------------------------------------------
> info: pulse-input: Server name: 'pulseaudio 8.0'
> info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> info: pulse-input: Started recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
> info: pulse-input: Server name: 'pulseaudio 8.0'
> info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> info: pulse-input: Started recording from 'alsa_input.pci-0000_00_14.2.analog-stereo'
> info: Switched to scene 'Scene'
> warning: Failed to glob scene collections
> warning: [rtmp-services plugin] Successfully updated file 'services.json' (version 82)
> warning: [rtmp-services plugin] Successfully updated package (version 82)
> info: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
> uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
> info: [obs-ndi] starting NDI main output with name 'LinuxGaming'
> info: [obs-ndi] 'LinuxGaming': ndi output started
> Illegal instruction (core dumped)

**Comment by airwasp** [comment] 2018-07-07 02:12
Apologies for double-post -- this may be of some value.

Here's a log of me:
-Starting OBS without OBS-NDI installed
-Closing OBS
-Installing OBS-NDI
-Trying to start OBS with OBS-NDI installed
-OBS refusing to start

Hope this helps!

> patrick@Patrick-Ubuntu:~$ obs
> Attempted path: share/obs/obs-studio/locale/en-US.ini
> Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
> Attempted path: share/obs/obs-studio/locale.ini
> Attempted path: /usr/share/obs/obs-studio/locale.ini
> Attempted path: share/obs/obs-studio/themes/Dark.qss
> Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
> Attempted path: share/obs/obs-studio/license/gplv2.txt
> Attempted path: /usr/share/obs/obs-studio/license/gplv2.txt
> info: CPU Name: AMD A4-3300M APU with Radeon(tm) HD Graphics
> info: CPU Speed: 1334.891MHz
> info: Physical Cores: 2, Logical Cores: 2
> info: Physical Memory: 5435MB Total, 3172MB Free
> info: Kernel Version: Linux 4.13.0-45-generic
> info: Distribution: "Ubuntu" "16.04"
> info: Portable mode: false
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
> QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
> info: OBS 21.1.0 (linux)
> info: ---------------------------------
> info: ---------------------------------
> info: audio settings reset:
> 	samples per sec: 44100
> 	speakers:        2
> info: ---------------------------------
> info: Initializing OpenGL...
> info: Loading up OpenGL on adapter X.Org AMD SUMO (DRM 2.50.0 / 4.13.0-45-generic, LLVM 6.0.0)
> info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 18.0.5, shading language 3.30
> info: ---------------------------------
> info: video settings reset:
> 	base resolution:   1600x900
> 	output resolution: 1280x720
> 	downscale filter:  Bicubic
> 	fps:               30/1
> 	format:            NV12
> 	YUV mode:          601/Partial
> info: Audio monitoring device:
> 	name: Default
> 	id: default
> info: ---------------------------------
> libDeckLinkAPI.so: cannot open shared object file: No such file or directory
> info: No blackmagic support
> error: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: cannot open shared object file: No such file or directory
> 
> info: Couldn't find VLC installation, VLC video source disabled
> info: ---------------------------------
> info:   Loaded Modules:
> info:     vlc-video.so
> info:     text-freetype2.so
> info:     rtmp-services.so
> info:     obs-x264.so
> info:     obs-transitions.so
> info:     obs-outputs.so
> info:     obs-libfdk.so
> info:     obs-filters.so
> info:     obs-ffmpeg.so
> info:     linux-v4l2.so
> info:     linux-pulseaudio.so
> info:     linux-jack.so
> info:     linux-decklink.so
> info:     linux-capture.so
> info:     linux-alsa.so
> info:     image-source.so
> info:     frontend-tools.so
> info: ---------------------------------
> info: ==== Startup complete ===============================================
> error: Service '' not found
> info: All scene data cleared
> info: ------------------------------------------------
> info: pulse-input: Server name: 'pulseaudio 8.0'
> info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> info: pulse-input: Started recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
> info: pulse-input: Server name: 'pulseaudio 8.0'
> info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> info: pulse-input: Started recording from 'alsa_input.pci-0000_00_14.2.analog-stereo'
> info: Switched to scene 'Scene'
> info: ------------------------------------------------
> info: Loaded scenes:
> info: - scene 'Scene':
> info: ------------------------------------------------
> info: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
> info: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
> info: ==== Shutting down ==================================================
> info: Switched to scene '(null)'
> info: pulse-input: Stopped recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
> info: pulse-input: Got 736 packets with 174959 frames
> info: pulse-input: Stopped recording from 'alsa_input.pci-0000_00_14.2.analog-stereo'
> info: pulse-input: Got 363 packets with 157708 frames
> info: All scene data cleared
> info: ------------------------------------------------
> info: Freeing OBS context data
> info: [Scripting] Total detached callbacks: 0
> info: == Profiler Results =============================
> info: run_program_init: 909.518 ms
> info:  ┣OBSApp::AppInit: 8.07 ms
> info:  ┃ ┗OBSApp::InitLocale: 2.549 ms
> info:  ┗OBSApp::OBSInit: 717.688 ms
> info:    ┣obs_startup: 18.914 ms
> info:    ┗OBSBasic::OBSInit: 497.853 ms
> info:      ┣OBSBasic::InitBasicConfig: 0.371 ms
> info:      ┣OBSBasic::ResetAudio: 0.494 ms
> info:      ┣OBSBasic::ResetVideo: 167.464 ms
> info:      ┣OBSBasic::InitOBSCallbacks: 0.011 ms
> info:      ┣OBSBasic::InitHotkeys: 0.078 ms
> info:      ┣obs_load_all_modules: 190.791 ms
> info:      ┃ ┣obs_init_module(frontend-tools.so): 94.794 ms
> info:      ┃ ┣obs_init_module(image-source.so): 0.007 ms
> info:      ┃ ┣obs_init_module(linux-alsa.so): 0.004 ms
> info:      ┃ ┣obs_init_module(linux-capture.so): 1.738 ms
> info:      ┃ ┣obs_init_module(linux-decklink.so): 0.217 ms
> info:      ┃ ┣obs_init_module(linux-jack.so): 0.005 ms
> info:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0.01 ms
> info:      ┃ ┣obs_init_module(linux-v4l2.so): 0.003 ms
> info:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.135 ms
> info:      ┃ ┃ ┗nvenc_check: 0.109 ms
> info:      ┃ ┣obs_init_module(obs-filters.so): 0.021 ms
> info:      ┃ ┣obs_init_module(obs-libfdk.so): 0.004 ms
> info:      ┃ ┣obs_init_module(obs-outputs.so): 0.006 ms
> info:      ┃ ┣obs_init_module(obs-transitions.so): 0.029 ms
> info:      ┃ ┣obs_init_module(obs-x264.so): 0.002 ms
> info:      ┃ ┣obs_init_module(rtmp-services.so): 0.239 ms
> info:      ┃ ┣obs_init_module(text-freetype2.so): 0.017 ms
> info:      ┃ ┗obs_init_module(vlc-video.so): 1.738 ms
> info:      ┣OBSBasic::ResetOutputs: 0.277 ms
> info:      ┣OBSBasic::CreateHotkeys: 0.051 ms
> info:      ┣OBSBasic::InitService: 2.155 ms
> info:      ┣OBSBasic::InitPrimitives: 0.825 ms
> info:      ┗OBSBasic::Load: 28.019 ms
> info: obs_hotkey_thread(25 ms): min=0.146 ms, median=0.362 ms, max=30.102 ms, 99th percentile=6.444 ms, 99.3671% below 25 ms
> info: audio_thread(Audio): min=0.047 ms, median=0.195 ms, max=1.145 ms, 99th percentile=0.774 ms
> info: obs_graphics_thread(33.3333 ms): min=1.107 ms, median=7.139 ms, max=27.227 ms, 99th percentile=17.87 ms, 100% below 33.333 ms
> info:  ┣tick_sources: min=0.001 ms, median=0.018 ms, max=0.142 ms, 99th percentile=0.069 ms
> info:  ┣output_frame: min=1.096 ms, median=5.814 ms, max=27.165 ms, 99th percentile=17.8 ms
> info:  ┃ ┣gs_context(video->graphics): min=1.095 ms, median=4.545 ms, max=27.164 ms, 99th percentile=15.847 ms
> info:  ┃ ┃ ┣render_video: min=0.862 ms, median=4.127 ms, max=26.959 ms, 99th percentile=15.141 ms
> info:  ┃ ┃ ┃ ┣render_main_texture: min=0.075 ms, median=0.116 ms, max=5.261 ms, 99th percentile=1.279 ms
> info:  ┃ ┃ ┃ ┣render_output_texture: min=0.006 ms, median=0.15 ms, max=26.824 ms, 99th percentile=0.76 ms
> info:  ┃ ┃ ┃ ┣render_convert_texture: min=0.004 ms, median=0.082 ms, max=2.763 ms, 99th percentile=0.134 ms
> info:  ┃ ┃ ┃ ┗stage_output_texture: min=0 ms, median=3.742 ms, max=13.175 ms, 99th percentile=9.679 ms
> info:  ┃ ┃ ┣download_frame: min=0 ms, median=0.016 ms, max=0.166 ms, 99th percentile=0.144 ms
> info:  ┃ ┃ ┗gs_flush: min=0.153 ms, median=0.298 ms, max=1.467 ms, 99th percentile=1.117 ms
> info:  ┃ ┗output_video_data: min=0.759 ms, median=1.184 ms, max=4.836 ms, 99th percentile=4.537 ms
> info:  ┗render_displays: min=0.006 ms, median=1.189 ms, max=10.504 ms, 99th percentile=5.569 ms
> info: video_thread(video): min=0 ms, median=0.002 ms, max=3.79 ms, 99th percentile=0.09 ms
> info: =================================================
> info: == Profiler Time Between Calls ==================
> info: obs_hotkey_thread(25 ms): min=25.239 ms, median=25.516 ms, max=31.816 ms, 45.8599% within ±2% of 25 ms (0% lower, 54.1401% higher)
> info: obs_graphics_thread(33.3333 ms): min=30.509 ms, median=33.336 ms, max=36.58 ms, 93.913% within ±2% of 33.333 ms (2.6087% lower, 3.47826% higher)
> info: =================================================
> info: Number of memory leaks: 0
> patrick@Patrick-Ubuntu:~$ #works fine - now let's install obs-ndi
> patrick@Patrick-Ubuntu:~$ sudo dpkg -i /home/patrick/Downloads/obs-ndi_1-ebd46a4-master-git-1_amd64.deb
> [sudo] password for patrick: 
> Selecting previously unselected package obs-ndi.
> (Reading database ... 213639 files and directories currently installed.)
> Preparing to unpack .../obs-ndi_1-ebd46a4-master-git-1_amd64.deb ...
> Unpacking obs-ndi (1-ebd46a4-master-git-1) ...
> Setting up obs-ndi (1-ebd46a4-master-git-1) ...
> patrick@Patrick-Ubuntu:~$ #Now let's start OBS again
> patrick@Patrick-Ubuntu:~$ obs
> Attempted path: share/obs/obs-studio/locale/en-US.ini
> Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
> Attempted path: share/obs/obs-studio/locale.ini
> Attempted path: /usr/share/obs/obs-studio/locale.ini
> Attempted path: share/obs/obs-studio/themes/Dark.qss
> Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
> Attempted path: share/obs/obs-studio/license/gplv2.txt
> Attempted path: /usr/share/obs/obs-studio/license/gplv2.txt
> info: CPU Name: AMD A4-3300M APU with Radeon(tm) HD Graphics
> info: CPU Speed: 1217.763MHz
> info: Physical Cores: 2, Logical Cores: 2
> info: Physical Memory: 5435MB Total, 3170MB Free
> info: Kernel Version: Linux 4.13.0-45-generic
> info: Distribution: "Ubuntu" "16.04"
> info: Portable mode: false
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
> QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
> info: OBS 21.1.0 (linux)
> info: ---------------------------------
> info: ---------------------------------
> info: audio settings reset:
> 	samples per sec: 44100
> 	speakers:        2
> info: ---------------------------------
> info: Initializing OpenGL...
> info: Loading up OpenGL on adapter X.Org AMD SUMO (DRM 2.50.0 / 4.13.0-45-generic, LLVM 6.0.0)
> info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 18.0.5, shading language 3.30
> info: ---------------------------------
> info: video settings reset:
> 	base resolution:   1600x900
> 	output resolution: 1280x720
> 	downscale filter:  Bicubic
> 	fps:               30/1
> 	format:            NV12
> 	YUV mode:          601/Partial
> info: Audio monitoring device:
> 	name: Default
> 	id: default
> info: ---------------------------------
> libDeckLinkAPI.so: cannot open shared object file: No such file or directory
> info: No blackmagic support
> info: [obs-ndi] hello ! (version 4.4.0)
> info: [obs-ndi] Trying ''
> info: [obs-ndi] Trying '/usr/lib'
> info: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.3'
> info: [obs-ndi] NDI runtime loaded successfully
> info: [obs-ndi] NDI library initialized successfully
> info: [obs-ndi] starting NDI main output with name 'LinuxGaming'
> info: [obs-ndi] 'LinuxGaming': ndi output started
> error: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: cannot open shared object file: No such file or directory
> 
> info: Couldn't find VLC installation, VLC video source disabled
> info: ---------------------------------
> info:   Loaded Modules:
> info:     vlc-video.so
> info:     text-freetype2.so
> info:     rtmp-services.so
> info:     obs-x264.so
> info:     obs-transitions.so
> info:     obs-outputs.so
> info:     obs-ndi.so
> info:     obs-libfdk.so
> info:     obs-filters.so
> info:     obs-ffmpeg.so
> info:     linux-v4l2.so
> info:     linux-pulseaudio.so
> info:     linux-jack.so
> info:     linux-decklink.so
> info:     linux-capture.so
> info:     linux-alsa.so
> info:     image-source.so
> info:     frontend-tools.so
> info: ---------------------------------
> info: ==== Startup complete ===============================================
> error: Service '' not found
> info: All scene data cleared
> info: ------------------------------------------------
> info: pulse-input: Server name: 'pulseaudio 8.0'
> info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> info: pulse-input: Started recording from 'alsa_output.pci-0000_00_14.2.analog-stereo.monitor'
> Illegal instruction (core dumped)
> patrick@Patrick-Ubuntu:~$ #No joy =[

**Comment by egro** [comment] 2019-07-28 22:17
I have the same problem, with very similar log outputs.

**Comment by codywohlers** [comment] 2020-04-21 03:45
I have the same issue.  After activating the "Main Output" on my `gaming-pc` the log ends in
[gaming-pc obs.txt](https://github.com/Palakis/obs-ndi/files/4507515/gaming-pc.obs.txt):

    ...
    info: [obs-ndi] starting NDI main output with name 'gaming-pc'
    info: [obs-ndi] 'gaming-pc': ndi output started


Then when I launch the `streaming-pc` with the scene already configured, OBS just crashes upon opening with the log ending in:
[streaming-pc obs.txt](https://github.com/Palakis/obs-ndi/files/4507524/streaming-pc.obs.txt):

    ...
    Illegal instruction (core dumped)

**Comment by codywohlers** [comment] 2020-04-28 16:01
I tried it on my `laptop-pc`, same distro but with an Nvidia GTX 650M, which can use the latest `nvidia` driver 440.82 and it works.

    ...
    info: [obs-ndi] starting NDI main output with name 'laptop-pc'
    info: [obs-ndi] 'laptop-pc': ndi output started
    info: [obs-ndi] stopping NDI main output
    info: Output 'NDI Main Output': stopping
    info: Output 'NDI Main Output': Total frames output: 1391
    info: Output 'NDI Main Output': Total drawn frames: 1391 (1392 attempted)
    info: Output 'NDI Main Output': Number of lagged frames due to rendering lag/stalls: 1 (0.1%)
[laptop-pc obs.txt](https://github.com/Palakis/obs-ndi/files/4546282/laptop-pc.obs.txt)

The only difference between `streaming-pc` (GT 650M) and `laptop-pc` (GTX 560) is the 560 has to use legacy Nvidia drivers (390.132 vs 440.82).  They both use OpenGL 3.3.  I notice @airwasp is using AMD and OpenGL 3.3.  Did it ever work with a newer `amdgpu` (mesa) version?

    SYSTEM        DRIVER          OpenGL  RESULTS
    ---------------------------------------------------------------------
    streaming-pc  nvidia 390.132  3.3     Illegal instruction
    laptop-pc     nvidia 440.82   3.3     works
    gaming-pc     amdgpu 20.1.0   4.6     works
    airwasp       amdgpu 18.0.5   3.3     Illegal instruction

I tried downgrading `laptop-pc` to Nvidia 390.132 and it still works.  I'm going to investigate further the differences between `streaming-pc` (GT 650M) and `laptop-pc` (GTX 560).  Is a there more comprehensive list of prerequisites/requirements other than [README.md](https://github.com/Palakis/obs-ndi/blob/master/README.md)?

**Comment by codywohlers** [comment] 2020-05-07 16:22
Since the problem appears to be with with `libndi` and not `obs-ndi` is this a NewTek problem?  Is there a bug report forum for NDI?

**Comment by jdslab** [comment] 2020-05-19 10:32
OP has an AMD A4 CPU. Could it be related to #33 , CPU not being supported?

**Comment by codywohlers** [comment] 2020-05-21 07:05
Yes that is most likely it.  Good catch.  I think this issue is a duplicate of #33 

    SYSTEM        CPU                   SSSE3  RESULTS
    ------------------------------------------------------------
    streaming-pc  AMD Phenom II X4 955  no     Illegal instruction
    laptop-pc     Intel i7-3615QM       yes    works
    gaming-pc     AMD Ryzen 5 2600X     yes    works
    airwasp       AMD A4-3300M          no     Illegal instruction

**Comment by royblumenthal** [comment] 2022-06-03 17:23
I'm not CERTAIN that this will solve your problem. But it solved mine, which was sort of similar to yours...

My issue was that on my two-pc setup, OBS on my originating machine would freeze up with no trigger event, leaving OBS on my streaming machine with a frozen image of whatever had been in the NDI feed last. The freezing seemed to follow no pattern. It could happen after 30 seconds or 2 minutes or 5 minutes. 

This was a mystery, because it used to work flawlessly. 

So I analysed what I was doing diffferently.

Instead of using a gigabyte lan connector box to connect both machines to my router, I was using wifi.

I'm guessing that something weird might be happening when there's network congestion, and tjhat it's causing an NDI-related memory leak, and that this happens mostly when there's a wifi to wifi relationship between the two machines.

With the lan connection box in play, I've had the crash happen once, but it was after an hour of problem-free use. Right now, I've been using it for at least two hours with no crash.

(Incidentally, the OBS crash logs don't seem to record the moment of death.)

My originating pc is a linux box running Zorin 16. My streaming box is a Windows 10 machine.

I hope this offers a thread of hope.

**Comment by royblumenthal** [comment] 2022-06-03 17:27
Oh... one more thing...

The crash only seemed to happen when the OBS scene I was sending via NDI was a Window Capture (Xcomposite) of my Krita drawing canvas. If I was using anything else, such as an automated looping slide show of images from a folder, it would work for hours. 

So maybe there's something strange going on with the Xcomposite rendering?

**Comment by paulpv** [comment] 2023-03-01 03:42
This seems fixed in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC; Closing.
Feel free to comment if you test and disagree and I should reopen.

**Closed by paulpv** 2023-03-01 03:42 UTC
Labels: bug, needs-investigation
