### ISSUE TITLE
Uninstall NDI 4.5.1 macOS runtime

### ISSUE THREAD

**Issue by saltarob** [Palakis/obs-ndi#837] opened 2023-02-13 19:26 UTC
Hi,

how do I uninstall NDI 4.5.1 macOS runtime? Where is it installed? How can I remove it completely?

Thank you.

**Comment by ohmywyattkane** [comment] 2023-02-17 00:11
They don't make an uninstaller, but here is the guide.
https://support.newtek.com/hc/en-us/articles/360058753994-How-to-Uninstall-NDI-Tools-for-Mac

**Comment by paulpv** [comment] 2023-02-28 01:00
Closing by design

**Closed by paulpv** 2023-02-28 01:00 UTC
Labels: question, wontfix, macos, not-plugin-related

**Comment by saltarob** [comment] 2023-02-28 11:45
Thank you for your reply. 
Unfortunately I cannot see any differentiation between the NDI 4.5.1 and the NDI 5 package which I also installed. Do the overwrite each other?
Also I see now the instruction you sent me are actually for NDI 5. Maybe NDI 4.5.1 is somewhere else?

**Comment by saltarob** [comment] 2023-03-01 16:02
I deleted the files pointed out in the provided link and reinstalled NDI 4.5.1. But no files were written to these directories. That files have nothing to do with NDI 4.5.1. The only reappeared after reinstalling NDI 5. That instructions are not valid to uninstall NDI 4.5.1.
